# The "brass" skin — piece prompts (exact size, wall to wall)

Thirteen pieces, each generated at the exact pixel size it is drawn, from the
whole-HUD template. For each: attach the template, put a red square around
the named piece, paste the block. Save the results as `1.png` … `13.png` and
run `python tools/build-fishing-skin.py`.

Sizes are the file's pixel size (the HUD's CSS size times the 1.2 scale).

## 1. `skin-brass-plate.png` — 518 × 584 (red square: the whole plate, frame and all)

```text
Attached is the reference template for a brass-and-walnut fishing game HUD. Reproduce the whole backplate marked with the red square as one image exactly 518 pixels wide by 584 pixels tall, wall to wall: the plate is a plain rectangle with square corners and it fills the entire image, with no margin and no green anywhere. Identical material and finish to the template: aged yellow brass with satin sheen and brown-green tarnish in the recesses, domed rivets, slot-head screws, and a field of dark oiled walnut wood with fine horizontal grain, dark enough that cream text reads on it. Soft diffuse lighting from the top left. The layout, in pixels measured from the top-left corner of the image: a brass rail 22 pixels wide runs around all four edges with a thin dark outer bevel, an engraved line parallel to the outer edge, a raised inner lip with a thin shadow, one domed rivet in each corner with the small engraved scroll flourish beside it, and evenly spaced domed rivets 8 pixels across down the left and right rails as in the template. Inside the top rail, spanning the full width between the left and right rails, a rivet bar from y 26 to y 38: a flat brass strip with a dark bevel top and bottom and one row of domed rivets 8 pixels across spaced evenly about 30 pixels apart. An identical bar inside the bottom rail from y 546 to y 558. Two thinner seams of the same design, 10 pixels tall, span the full width between the rails at y 393 to 403 and at y 457 to 467. Everything else inside the rails is the walnut field. Resting on the wood, faint and low-contrast as if oiled into the shadow, never bright and never in the centre: a rusty fishing hook with a short tail of line lying in the left margin at about x 30 to 55, y 170 to 230; a small carved wooden lure with a treble hook lying in the right margin at about x 462 to 494, y 200 to 260; a loose coil of fishing line in the lower left at about x 30 to 70, y 300 to 380; a small cork float on its side in the lower right at about x 460 to 494, y 300 to 360. Each item is darker than the brass, blends into the wood, and casts only a soft contact shadow. The bottom-right 200 by 200 pixels of the plate carries nothing beyond plain rail and plain wood, because the game lays a reel emblem over it. Front-on orthographic view, no perspective, no tilt, no text, no letters, no numbers, no logos, no watermark. Photoreal game-UI asset, crisp edges, high detail, PNG.
```

## 2. `skin-brass-plaque.png` — 283 × 53 (red square: the nameplate)

```text
Attached is the reference template for a brass-and-walnut fishing game HUD. Reproduce the engraved brass nameplate marked with the red square as one image exactly 283 pixels wide by 53 pixels tall, wall to wall: the plaque's outer edges touch all four edges of the image with no margin, and the only green is the flat chroma-key green, hex #00FF00, in the four small notches left by its scalloped corners. Identical to the template's plaque: a flat rectangle of aged yellow brass with satin sheen and faint brown tarnish, its four corners cut in shallow concave scallops 7 pixels across, a single engraved border line 4 pixels inside the edge all the way round, and one slot-head brass screw 10 pixels across at each end, centred 14 pixels in from the end and vertically centred. The whole middle of the plaque between the screws is plain smooth brass with no engraving and no change of tone, because the game writes a name over it. Front-on orthographic view, no perspective, no text, no letters, no logos, no watermark, no shadow on the green, no green spill on the brass edges. Photoreal game-UI asset, crisp edges, high detail, PNG.
```

## 3. `skin-brass-slot.png` — 41 × 41 (red square: one fish slot)

```text
Attached is the reference template for a brass-and-walnut fishing game HUD. Reproduce one of the square recessed fish slots marked with the red square as one image exactly 41 pixels wide by 41 pixels tall, wall to wall: the slot's outer edges touch all four edges of the image with no margin, and the only green is the flat chroma-key green, hex #00FF00, in the four tiny corners outside its rounded outline. Identical to the template's slots: a square bezel of aged yellow brass 6 pixels wide with rounded outer corners of 4 pixel radius, a 1 pixel dark bevel outside and a 1 pixel bright lip inside, one tiny slot-head screw 3 pixels across at each corner of the bezel, and inside the bezel a recessed square of dark oxidised steel, near black with a faint blue-grey cast, with a soft inner shadow along its top and left edges. The steel centre is plain and even, because the game lays a fish picture into it. Front-on orthographic view, no perspective, no text, no logos, no watermark, no shadow on the green, no green spill on the brass edges. Photoreal game-UI asset, crisp edges, high detail, PNG.
```

## 4. `skin-brass-window.png` — 451 × 101 (red square: the water window frame)

```text
Attached is the reference template for a brass-and-walnut fishing game HUD. Reproduce the rectangular brass window frame marked with the red square as one image exactly 451 pixels wide by 101 pixels tall, wall to wall: the frame's outer edges touch all four edges of the image with no margin. The only green is the flat chroma-key green, hex #00FF00, in the four small corners outside its rounded outline and across the entire inside of the frame, a rectangle 423 by 73 pixels, which must be completely empty, not dark, because the game draws water there. Identical to the template's window: a frame of aged yellow brass 14 pixels wide on all four sides with satin sheen and brown-green tarnish, a 1 pixel dark outer bevel, an inner edge that steps down in a raised brass lip and then a thin black rubber gasket, and one domed brass rivet 7 pixels across in each of the four corners of the frame, centred 7 pixels in from both edges. The four straight lengths between the corners are plain brass. Front-on orthographic view, no perspective, no text, no logos, no watermark, no shadow on the green, no green spill on the brass edges. Photoreal game-UI asset, crisp edges, high detail, PNG.
```

## 5. `skin-brass-track-wide.png` — 437 × 29 (red square: one gauge channel; this is the long one)

```text
Attached is the reference template for a brass-and-walnut fishing game HUD. Reproduce one of the slim brass gauge channels marked with the red square, in exactly the same design and material but at this size, as one image exactly 437 pixels wide by 29 pixels tall, wall to wall: the channel's outer edges touch all four edges of the image with no margin, and the only green is the flat chroma-key green, hex #00FF00, in the four small corners outside its fully rounded ends. A slim frame of aged yellow brass with satin sheen and brown-green tarnish, fully rounded ends of 14 pixel radius, a 1 pixel dark outer bevel, brass rails 5 pixels thick along the top and bottom, brass ends 17 pixels long each carrying one slot-head screw 9 pixels across centred vertically, and inside it a recessed channel of dark oxidised steel with a soft inner shadow along its top edge, plain and even from end to end with no marks or divisions, because the game draws a coloured fill inside it. Front-on orthographic view, no perspective, no text, no logos, no watermark, no shadow on the green, no green spill on the brass edges. Photoreal game-UI asset, crisp edges, high detail, PNG.
```

## 6. `skin-brass-track.png` — 194 × 26 (red square: one gauge channel)

```text
Attached is the reference template for a brass-and-walnut fishing game HUD. Reproduce one of the slim brass gauge channels marked with the red square, in exactly the same design and material but at this size, as one image exactly 194 pixels wide by 26 pixels tall, wall to wall: the channel's outer edges touch all four edges of the image with no margin, and the only green is the flat chroma-key green, hex #00FF00, in the four small corners outside its fully rounded ends. A slim frame of aged yellow brass with satin sheen and brown-green tarnish, fully rounded ends of 13 pixel radius, a 1 pixel dark outer bevel, brass rails 5 pixels thick along the top and bottom, brass ends 17 pixels long each carrying one slot-head screw 8 pixels across centred vertically, and inside it a recessed channel of dark oxidised steel with a soft inner shadow along its top edge, plain and even from end to end, because the game draws a coloured fill inside it. Front-on orthographic view, no perspective, no text, no logos, no watermark, no shadow on the green, no green spill on the brass edges. Photoreal game-UI asset, crisp edges, high detail, PNG.
```

## 7. `skin-brass-track-pull.png` — 446 × 31 (red square: one gauge channel; this is the pull bar)

```text
Attached is the reference template for a brass-and-walnut fishing game HUD. Reproduce one of the slim brass gauge channels marked with the red square, in exactly the same design and material but at this size, as one image exactly 446 pixels wide by 31 pixels tall, wall to wall: the channel's outer edges touch all four edges of the image with no margin, and the only green is the flat chroma-key green, hex #00FF00, in the four small corners outside its fully rounded ends. A slim frame of aged yellow brass with satin sheen and brown-green tarnish, fully rounded ends of 15 pixel radius, a 1 pixel dark outer bevel, brass rails 5 pixels thick along the top and bottom, brass ends 17 pixels long each carrying one slot-head screw 9 pixels across centred vertically, and inside it a recessed channel of dark oxidised steel with a soft inner shadow along its top edge, plain and even from end to end with no marks, no divisions and no centre line, because the game draws zone tints and a pointer inside it. Front-on orthographic view, no perspective, no text, no logos, no watermark, no shadow on the green, no green spill on the brass edges. Photoreal game-UI asset, crisp edges, high detail, PNG.
```

## 8. `skin-brass-track-slim.png` — 353 × 22 (red square: one gauge channel; this is the thin one)

```text
Attached is the reference template for a brass-and-walnut fishing game HUD. Reproduce one of the slim brass gauge channels marked with the red square, in exactly the same design and material but at this size, as one image exactly 353 pixels wide by 22 pixels tall, wall to wall: the channel's outer edges touch all four edges of the image with no margin, and the only green is the flat chroma-key green, hex #00FF00, in the four small corners outside its fully rounded ends. A slim frame of aged yellow brass with satin sheen and brown-green tarnish, fully rounded ends of 11 pixel radius, a 1 pixel dark outer bevel, brass rails 4 pixels thick along the top and bottom, brass ends 14 pixels long each carrying one slot-head screw 7 pixels across centred vertically, and inside it a recessed channel of dark oxidised steel with a soft inner shadow along its top edge, plain and even from end to end, because the game draws a coloured fill inside it. Front-on orthographic view, no perspective, no text, no logos, no watermark, no shadow on the green, no green spill on the brass edges. Photoreal game-UI asset, crisp edges, high detail, PNG.
```

## 9. `skin-brass-key.png` — 31 × 31 (red square: the small key cap between the two gauges)

```text
Attached is the reference template for a brass-and-walnut fishing game HUD. Reproduce the small square brass key cap marked with the red square as one image exactly 31 pixels wide by 31 pixels tall, wall to wall: the key cap's outer edges touch all four edges of the image with no margin, and the only green is the flat chroma-key green, hex #00FF00, in the four tiny corners outside its rounded outline. Identical to the template's key caps: a square button of aged yellow brass with satin sheen and brown-green tarnish in the recesses, rounded corners of 5 pixel radius, a bevelled rim 6 pixels wide sloping inward with a 1 pixel dark line along its outer edge and a bright highlight along the top and left of the rim, and a flat, slightly darker brass face inside the rim, plain and smooth with no engraving, because the game writes a letter on it. Front-on orthographic view, no perspective, no text, no letters, no logos, no watermark, no shadow on the green, no green spill on the brass edges. Photoreal game-UI asset, crisp edges, high detail, PNG.
```

## 10. `skin-brass-key-wide.png` — 53 × 35 (red square: one of the three key caps in the lower row)

```text
Attached is the reference template for a brass-and-walnut fishing game HUD. Reproduce one of the square brass key caps in the lower row marked with the red square, in exactly the same design and material but slightly wider than tall, as one image exactly 53 pixels wide by 35 pixels tall, wall to wall: the key cap's outer edges touch all four edges of the image with no margin, and the only green is the flat chroma-key green, hex #00FF00, in the four tiny corners outside its rounded outline. A rounded-rectangle button of aged yellow brass with satin sheen and brown-green tarnish in the recesses, corner radius 6 pixels, a bevelled rim 6 pixels wide sloping inward with a 1 pixel dark line along its outer edge and a bright highlight along the top and left of the rim, and a flat, slightly darker brass face inside the rim, plain and smooth with no engraving, because the game writes a key name on it. Front-on orthographic view, no perspective, no text, no letters, no logos, no watermark, no shadow on the green, no green spill on the brass edges. Photoreal game-UI asset, crisp edges, high detail, PNG.
```

## 11. `skin-brass-needle.png` — 12 × 19 (red square: one gauge channel, for the material; the pointer is new)

```text
Attached is the reference template for a brass-and-walnut fishing game HUD. The piece marked with the red square is one of the brass gauge channels; make a pointer for it in exactly the same material and finish, as one image exactly 12 pixels wide by 19 pixels tall, wall to wall: the pointer's top and bottom ends touch the top and bottom edges of the image, and the only green is the flat chroma-key green, hex #00FF00, in the 2 pixel strips down its left and right sides. The pointer is a slim upright bar of aged yellow brass, 8 pixels wide and the full 19 pixels tall, centred left-to-right, with fully rounded ends, a bright vertical highlight down its left third, a 1 pixel dark bevel around its outline, and one tiny slot-head screw 4 pixels across at its vertical centre. Front-on orthographic view, no perspective, no text, no logos, no watermark, no shadow on the green, no green spill on the brass edges. Photoreal game-UI asset, crisp edges, high detail, PNG.
```

## 12. `skin-brass-menu.png` — 360 × 384 (red square: the whole plate, frame and all; this is a smaller plain one)

```text
Attached is the reference template for a brass-and-walnut fishing game HUD. Reproduce the backplate marked with the red square, in exactly the same design and material but smaller and plainer, as one image exactly 360 pixels wide by 384 pixels tall, wall to wall: the plate is a plain rectangle with square corners that fills the entire image, with no margin and no green anywhere. Identical material to the template: aged yellow brass with satin sheen and brown-green tarnish, domed rivets, and a field of dark oiled walnut wood with fine horizontal grain, dark enough that cream text reads on it. A brass rail 22 pixels wide runs around all four edges with a thin dark outer bevel, an engraved line parallel to the outer edge, a raised inner lip with a thin shadow, one domed rivet in each corner with the small engraved scroll flourish beside it, and evenly spaced domed rivets 8 pixels across down the left and right rails. Inside the top rail, spanning the full width between the left and right rails, a rivet bar from y 26 to y 38, a flat brass strip with a dark bevel top and bottom and one row of domed rivets 8 pixels across spaced evenly about 30 pixels apart, and an identical bar inside the bottom rail from y 346 to y 358. Everything else inside the rails is plain walnut with nothing on it, because the game lays a list over it. Front-on orthographic view, no perspective, no tilt, no text, no letters, no logos, no watermark. Photoreal game-UI asset, crisp edges, high detail, PNG.
```

## 13. `skin-brass-button.png` — 283 × 48 (red square: one key cap; this is a wide button of the same design)

```text
Attached is the reference template for a brass-and-walnut fishing game HUD. Reproduce one of the square brass key caps marked with the red square as a wide push button in exactly the same design and material, as one image exactly 283 pixels wide by 48 pixels tall, wall to wall: the button's outer edges touch all four edges of the image with no margin, and the only green is the flat chroma-key green, hex #00FF00, in the four small corners outside its rounded outline. A rounded rectangle of aged yellow brass with satin sheen and brown-green tarnish in the recesses, corner radius 8 pixels, a bevelled rim 8 pixels wide sloping inward with a 1 pixel dark line along its outer edge and a bright highlight along the top and left of the rim, and a flat, slightly darker brass face inside the rim, plain and smooth with no engraving, because the game writes a label on it. Front-on orthographic view, no perspective, no text, no letters, no logos, no watermark, no shadow on the green, no green spill on the brass edges. Photoreal game-UI asset, crisp edges, high detail, PNG.
```
