-- ============================================================================
--  poggy_tickets · every piece of text players and staff read
--  The language used is Config.Language (config.lua). %s and %d are filled in
--  by the script: keep them, in the same order.
-- ============================================================================

Translations = {
    ["en"] = {
        -- Priorities and states
        ["priority_urgent"] = "Urgent",
        ["priority_high"]   = "High",
        ["priority_medium"] = "Medium",
        ["priority_low"]    = "Low",
        ["status_open"]     = "Open",
        ["status_claimed"]  = "Claimed",
        ["status_closed"]   = "Closed",
        ["close_resolved"]  = "Resolved",
        ["close_noaction"]  = "No action needed",
        ["close_duplicate"] = "Duplicate",
        ["close_invalid"]   = "Invalid",
        ["role_admin"]      = "Admin",
        ["role_mod"]        = "Mod",
        ["role_helper"]     = "Helper",
        ["role_developer"]  = "Developer",

        -- The player's window
        ["ui_title"]            = "Tickets",
        ["ui_tab_new"]          = "New ticket",
        ["ui_tab_mine"]         = "My tickets",
        ["ui_category"]         = "What is it about?",
        ["ui_priority"]         = "How urgent is it?",
        ["ui_description"]      = "What happened?",
        ["ui_description_hint"] = "Say what happened, where and when. The more detail, the faster we can help.",
        ["ui_reported"]         = "Which player?",
        ["ui_reported_none"]    = "Nobody close by. You can describe them above.",
        ["ui_reported_skip"]    = "I don't know / not listed",
        ["ui_clip"]             = "Video link (optional)",
        ["ui_clip_hint"]        = "A clip helps us more than anything else. If you have one, paste the link here.",
        ["ui_presence"]         = "I would like a staff member to come to me",
        ["ui_submit"]           = "Send ticket",
        ["ui_help_button"]      = "I need help right now",
        ["ui_choose_title"]         = "What do you need?",
        ["ui_choice_ticket_title"]  = "Send a ticket",
        ["ui_choice_ticket_text"]   = "Report a bug, a cheater or another player, or ask for something to be looked into. You fill in a short form and staff answer it.",
        ["ui_no_messages"]          = "No messages yet.",
        ["ui_help_hint"]        = "Stuck, downed or lost? One press calls staff to where you are. No form, no ticket.",
        ["ui_position_note"]    = "Your position is saved with the ticket.",
        ["ui_no_tickets"]       = "You have no tickets.",
        ["ui_reply"]            = "Write a reply",
        ["ui_send"]             = "Send",
        ["ui_close"]            = "Close",
        ["ui_back"]             = "Back",
        ["ui_you"]              = "You",
        ["ui_staff"]            = "Staff",
        ["ui_claimed_by"]       = "Handled by %s",
        ["ui_waiting"]          = "Waiting for staff",
        ["ui_closed_as"]        = "Closed: %s",

        -- The staff panel
        ["sp_title"]         = "Tickets",
        ["sp_tab_tickets"]   = "Tickets",
        ["sp_tab_bans"]      = "Bans",
        ["sp_tab_players"]   = "Players",
        ["pl_search"]        = "Filter, or press Enter to find someone who has left",
        ["pl_online"]        = "Online",
        ["pl_found"]         = "Found",
        ["pl_pick"]          = "Pick a player.",
        ["pl_clean"]         = "Nothing on record.",
        ["pl_warnings"]      = "Warnings",
        ["pl_tickets"]       = "Tickets",
        ["pl_bans"]          = "Bans",
        ["pl_reported"]      = "reported",
        ["pl_sent"]          = "sent by them",
        ["pl_unread"]        = "not read yet",
        ["pl_counts"]        = "%d warnings · reported %d times",
        ["pl_record"]        = "Record",
        ["pl_open_ticket"]   = "Open",
        ["pl_staff"]         = "staff",
        ["sp_bar_player"]    = "Player",
        ["sp_goto"]          = "Go to",
        ["sp_tab_staff"]     = "Staff",
        ["sp_tab_audit"]     = "Audit",
        ["sp_on_duty"]       = "On duty",
        ["sp_off_duty"]      = "Off duty",
        ["sp_search"]        = "Search",
        ["sp_filter_open"]   = "Open",
        ["sp_filter_claimed"] = "Claimed",
        ["sp_filter_mine"]   = "Mine",
        ["sp_filter_closed"] = "Closed",
        ["sp_filter_online"] = "Online only",
        ["sp_sort_age"]      = "Oldest first",
        ["sp_sort_priority"] = "Most urgent first",
        ["sp_none"]          = "Nothing here.",
        ["sp_pick"]          = "Pick a ticket.",
        ["sp_player"]        = "Player",
        ["sp_reported"]      = "Reported player",
        ["sp_online"]        = "online",
        ["sp_offline"]       = "offline",
        ["sp_where"]         = "Where",
        ["sp_sent"]          = "Sent",
        ["sp_wants_presence"] = "Asked for a staff member to come",
        ["sp_clip"]          = "Video link",
        ["sp_copy"]          = "Copy",
        ["sp_copied"]        = "Copied",
        ["sp_history"]       = "%d tickets · %d warnings",
        ["sp_conversation"]  = "Conversation",
        ["sp_claim"]         = "Claim",
        ["sp_unclaim"]       = "Release",
        ["sp_assign"]        = "Assign",
        ["sp_assign_to"]     = "Assign to",
        ["sp_category"]      = "Kind",
        ["sp_priority"]      = "Priority",
        ["sp_goto_player"]   = "Player",
        ["sp_goto_place"]    = "Ticket location",
        ["sp_return"]        = "Return",
        ["sp_close_ticket"]  = "Close ticket",
        ["sp_close_reason"]  = "Why is it closed?",
        ["sp_note"]          = "Note (the player reads this)",
        ["sp_warn"]          = "Warn",
        ["sp_kick"]          = "Kick",
        ["sp_ban"]           = "Ban",
        ["sp_reason"]        = "Reason (the player reads this)",
        ["sp_ban_length"]    = "For how long?",
        ["sp_ban_cheat"]     = "This is for cheating",
        ["sp_len_perm"]      = "Permanent",
        ["sp_len_1d"]        = "1 day",
        ["sp_len_3d"]        = "3 days",
        ["sp_len_7d"]        = "7 days",
        ["sp_len_30d"]       = "30 days",
        ["sp_confirm"]       = "Confirm",
        ["sp_cancel"]        = "Cancel",
        ["sp_staff_offline"] = "staff offline",
        ["sp_help_strip"]    = "Help requests",
        ["sp_help_respond"]  = "Responding",
        ["sp_help_by"]       = "%s is responding",
        ["sp_help_done"]     = "Done",
        ["sp_unban"]         = "Lift ban",
        ["sp_unban_reason"]  = "Why is it lifted?",
        ["sp_ban_active"]    = "Active",
        ["sp_ban_lifted"]    = "Lifted",
        ["sp_ban_expired"]   = "Expired",
        ["sp_ban_left"]      = "%s left",
        ["sp_hire"]          = "Add staff",
        ["sp_hire_search"]   = "Search every character, online or not",
        ["sp_hire_roles"]    = "Roles",
        ["sp_save"]          = "Save",
        ["sp_remove"]        = "Remove",
        ["sp_framework_admin"] = "server admin",
        ["sp_audit_who"]     = "Who",
        ["sp_audit_action"]  = "Action",
        ["sp_audit_all"]     = "All",
        ["sp_audit_ticket"]  = "Ticket",
        ["sp_today"]         = "Today",
        ["sp_yesterday"]     = "Yesterday",
        ["sp_history_btn"]   = "History",
        ["sp_bar_ticket"]    = "Ticket",
        ["sp_bar_go"]        = "Go to",
        ["sp_goto_short"]    = "Go",
        ["sp_filter_kind"]   = "Kind",
        ["sp_filter_priority"] = "Priority",
        ["sp_count"]         = "%d shown",

        -- The audit timeline: "<name> <this text> <target>"
        ["au_g_tickets"]     = "Tickets",
        ["au_g_moderation"]  = "Moderation",
        ["au_g_movement"]    = "Movement",
        ["au_g_staff"]       = "Staff",
        ["au_claim"]         = "claimed the ticket from",
        ["au_release"]       = "released the ticket held by",
        ["au_assign"]        = "gave the ticket to",
        ["au_reply"]         = "replied to",
        ["au_category"]      = "changed the kind",
        ["au_priority"]      = "changed the priority",
        ["au_close"]         = "closed the ticket from",
        ["au_warn"]          = "warned",
        ["au_kick"]          = "kicked",
        ["au_ban"]           = "banned",
        ["au_unban"]         = "lifted ban",
        ["au_teleport"]      = "teleported to",
        ["au_return"]        = "returned to where they were",
        ["au_invis_on"]      = "went invisible",
        ["au_invis_off"]     = "became visible",
        ["au_duty"]          = "changed duty",
        ["au_staff_hire"]    = "added staff:",
        ["au_staff_roles"]   = "changed the roles of",
        ["au_staff_remove"]  = "removed staff:",
        ["au_help_respond"]  = "answered a help request from",

        -- Pop-ups (bottom right)
        ["toast_new_ticket"]   = "New ticket #%d: %s (%s)",
        ["toast_new_help"]     = "%s needs help near %s",
        ["toast_claimed"]      = "Ticket #%d: %s is on it.",
        ["toast_assigned"]     = "Ticket #%d was given to %s.",
        ["toast_assigned_you"] = "Ticket #%d was given to you.",
        ["toast_reply"]        = "Ticket #%d: new reply from %s.",
        ["toast_closed"]       = "Ticket #%d was closed: %s",
        ["toast_help_coming"]  = "%s is on the way to help you.",
        ["toast_updates"]      = "You have news on %d ticket(s). Type /%s to read it.",
        ["toast_network_flag"] = "%s joined. Banned for cheating on %d other server(s).",

        -- Messages
        ["msg_sent"]           = "Ticket #%d sent.",
        ["msg_no_staff"]       = "No staff are on right now. Your ticket is saved and will be looked at.",
        ["msg_cooldown"]       = "You can send another ticket in %d minute(s).",
        ["msg_too_many"]       = "You already have %d open tickets. Wait for one to be closed.",
        ["msg_need_text"]      = "Please say what happened.",
        ["msg_bad_clip"]       = "The video link must start with http:// or https://",
        ["msg_no_char"]        = "Pick a character first.",
        ["msg_help_sent"]      = "Staff have been called.",
        ["msg_help_none"]      = "Staff have been called, but none are on right now. Send a ticket so it is not lost.",
        ["msg_help_cooldown"]  = "You can call for help again in %d minute(s).",
        ["msg_not_staff"]      = "That is for staff.",
        ["msg_not_allowed"]    = "Your role cannot do that.",
        ["msg_not_found"]      = "That ticket is gone.",
        ["msg_already_claimed"] = "%s already has that ticket.",
        ["msg_player_offline"] = "That player is not online.",
        ["msg_need_reason"]    = "Give a reason.",
        ["msg_duty_on"]        = "You are on duty.",
        ["msg_duty_off"]       = "You are off duty until you turn it back on or log in again.",
        ["msg_invis_on"]       = "You are invisible.",
        ["msg_invis_off"]      = "You are visible.",
        ["msg_no_return"]      = "There is nowhere to return to.",
        ["msg_kicked"]         = "Kicked by staff: %s",
        ["msg_done"]           = "Done.",

        -- The warning screen
        ["warn_title"]  = "Warning from staff",
        ["warn_button"] = "I understand",
        ["warn_wait"]   = "Read it first…",

        -- Discord
        ["dc_new"]      = "New ticket",
        ["dc_claimed"]  = "Claimed by %s",
        ["dc_solved"]   = "Closed by %s: %s",
        ["dc_took"]     = "Open for %s",
    },
}
