-- ============================================================================
--  poggy_chess · words
--  Every sentence a player reads. Config.Language picks the language. %s is
--  filled with a name or an amount, %d with a number; keep them in each line.
--  The NUI block is the table page.
-- ============================================================================

Translations = Translations or {}

Translations.en = {
    -- money
    ["money_cash"] = "$%d",
    ["money_gold"] = "%d gold",

    -- the map and the prompts
    ["blip_name"] = "Chess Table",
    ["prompt_group"] = "Chess & Checkers",
    ["prompt_sit_white"] = "Sit (White / Red side)",
    ["prompt_sit_black"] = "Sit (Black side)",
    ["prompt_stand"] = "Stand up",
    ["prompt_camera"] = "Change view",
    ["prompt_draw"] = "Offer a draw",
    ["prompt_hint"] = "Hint",
    ["prompt_claim"] = "Claim the win",
    ["prompt_resign"] = "Resign",
    ["ai_name"] = "Local Patron",

    -- sitting down
    ["seat_taken"] = "Someone is already sitting there.",
    ["already_seated"] = "You are already sitting at a table.",
    ["seat_too_far"] = "Get closer to the chair.",
    ["no_character"] = "Your character is not ready yet.",

    -- setting up
    ["bad_request"] = "That did not work. Try again.",
    ["game_disabled"] = "That game is not played at these tables.",
    ["ai_disabled"] = "There is nobody to play against here.",
    ["ai_seat_taken"] = "The other chair is taken: invite that player instead.",
    ["bad_level"] = "Pick a difficulty.",
    ["wagers_off"] = "Wagers are not allowed here.",
    ["wager_range"] = "A wager must be between %s and %s.",
    ["cant_afford_wager"] = "You cannot afford that wager.",
    ["opponent_cant_afford"] = "%s cannot afford the wager. Nothing was taken.",
    ["resume_not_found"] = "That game cannot be picked up from this chair.",
    ["resume_in_play"] = "That game is already being played at another table.",
    ["resume_wrong_player"] = "This saved game is %s's. Only they can take that chair for it.",
    ["invite_declined"] = "%s declined your game.",
    ["clock_bad"] = "That clock is not allowed here. Pick another time.",

    -- playing
    ["not_your_turn"] = "It is not your turn.",
    ["illegal_move"] = "That move is not allowed.",
    ["draw_pending"] = "A draw offer is already waiting for an answer.",
    ["draw_wait"] = "Make a move before offering another draw.",
    ["draw_offer_sent"] = "Draw offered. Waiting for an answer.",
    ["draw_declined"] = "%s declined your draw offer.",
    ["draw_declined_ai"] = "%s would rather play on.",
    ["idle_not_yet"] = "Your opponent still has time to move.",
    ["hint_your_turn"] = "Hints are for your own turn.",
    ["hint_cooldown"] = "Next hint in %d seconds.",
    ["hint_none"] = "No hint for this position.",
    ["opponent_left_saved"] = "%s left the table. The game is saved: either of you can pick it up from the start menu.",
    ["death_ended"] = "The game is over: %s died.",
    ["stood_away"] = "You were stood up: you are too far from the table.",
    ["stood_admin"] = "An admin reset the table.",

    -- wagers
    ["wager_won"] = "You won the %s wager.",
    ["wager_won_later"] = "You won the %s wager. The winnings are paid next time you are here.",
    ["wager_lost"] = "You lost the %s wager.",
    ["wager_refunded"] = "Your %s stake has been returned.",
    ["payout_paid"] = "Chess tables: %s owed to you has been paid.",

    -- admin
    ["admin_no_table"] = "There is no table called %s.",
    ["admin_reset"] = "Table %s is reset: any game ended with no result and the chairs emptied.",
    ["admin_rerate"] = "Ratings worked out again from %d rated game(s).",

    -- ─── the table page ─────────────────────────────────────────────────────
    NUI = {
        ["money_cash"] = "$%d",
        ["money_gold"] = "%d gold",
        ["close"] = "Close",
        ["cancel"] = "Cancel",
        ["continue"] = "Continue",
        ["accept"] = "Accept",
        ["decline"] = "Decline",
        ["stand_up"] = "Stand up",
        ["my_record"] = "My record",
        ["resume"] = "Resume",
        ["review"] = "Review",
        ["loading"] = "Loading...",
        ["you"] = "You",
        ["ai_tag"] = "AI",

        ["game_chess"] = "Chess",
        ["game_checkers"] = "Checkers",
        ["game_checkers_variant"] = "%s checkers",
        ["colour_white"] = "White",
        ["colour_black"] = "Black",
        ["colour_red"] = "Red",
        ["you_play"] = "You play %s",
        ["you_played"] = "You played %s",
        ["vs_name"] = "vs %s",
        ["vs_ai"] = "vs AI · %s",
        ["moves_count"] = "%d moves",
        ["moves_count_one"] = "%d move",
        ["your_turn"] = "your move",
        ["their_turn"] = "their move",
        ["stake_pill"] = "Stake %s",
        ["clock_pill"] = "Clock %s",

        -- difficulty levels (a level with no line here shows its id)
        ["level_beginner"] = "Beginner",
        ["level_novice"] = "Novice",
        ["level_casual"] = "Casual",
        ["level_club"] = "Club player",
        ["level_advanced"] = "Advanced",
        ["level_expert"] = "Expert",
        ["level_grandmaster"] = "Grandmaster",
        ["level_easy"] = "Easy",
        ["level_medium"] = "Medium",
        ["level_hard"] = "Hard",

        -- variants
        ["variant_american"] = "American",
        ["variant_russian"] = "Russian",
        ["variant_brazilian"] = "Brazilian",
        ["variant_pool"] = "Pool",
        ["variant_custom"] = "House",
        ["variant_american_short"] = "The classic: short kings, men capture forwards only.",
        ["variant_russian_short"] = "Flying kings; a man crowned mid-capture keeps going.",
        ["variant_brazilian_short"] = "International rules on this board: you must take the most pieces.",
        ["variant_pool_short"] = "Flying kings and backward captures, any capture you like.",
        ["variant_custom_short"] = "Pick every rule yourself.",
        ["variant_american_desc"] = "English draughts, the game most people know as checkers. Black moves first, kings move one square at a time, and a man crowned during a capture stops there.",
        ["variant_russian_desc"] = "Shashki. Men capture backwards as well as forwards, kings fly along the diagonals, and a man that reaches the far row in the middle of a capture is crowned and carries on capturing as a king.",
        ["variant_brazilian_desc"] = "International draughts played on an 8 by 8 board. Men capture backwards, kings fly, and of all the captures you must play the one that takes the most pieces.",
        ["variant_pool_desc"] = "The American pool game. Black moves first, men capture backwards, kings fly, and you may choose any capture, even a shorter one.",
        ["variant_custom_desc"] = "House rules, picked at the table.",

        -- the rules card
        ["rule_first_red"] = "Red moves first.",
        ["rule_first_black"] = "Black moves first.",
        ["rule_men_forward"] = "Men move and capture forwards only.",
        ["rule_men_back"] = "Men move forwards, but capture backwards too.",
        ["rule_kings_short"] = "Kings move and capture one square in any direction.",
        ["rule_kings_fly"] = "Kings fly: they move and capture along a whole diagonal.",
        ["rule_must_capture"] = "Capturing is compulsory: if you can take, you must. You may choose which capture.",
        ["rule_max_capture"] = "Capturing is compulsory, and you must play the capture that takes the most pieces.",
        ["rule_optional_capture"] = "Capturing is optional.",
        ["rule_multi"] = "A capture goes on while there is more to take. Taken pieces come off when the move ends, and none can be jumped twice.",
        ["rule_crown_stop"] = "A man reaching the far row is crowned, and its move ends there.",
        ["rule_crown_continue"] = "A man reaching the far row in the middle of a capture is crowned and keeps capturing as a king.",
        ["rule_crown_pass"] = "A man that passes the far row in the middle of a capture keeps capturing as a man; it is crowned only if it ends there.",
        ["rule_blocked_loses"] = "A player who has no pieces left, or cannot move, loses.",
        ["rule_blocked_draws"] = "A player with no pieces left loses; one who cannot move draws.",
        ["rule_draws_both"] = "Drawn when the same position comes up %d times, or after %d moves each with no capture and no man moved.",
        ["rule_draws_rep"] = "Drawn when the same position comes up %d times.",
        ["rule_draws_quiet"] = "Drawn after %d moves each with no capture and no man moved.",
        ["rule_chess_1"] = "Standard chess: castling, en passant and promotion to any piece.",
        ["rule_chess_2"] = "Drawn by stalemate, the same position three times, fifty moves each without a capture or pawn move, or when neither side can checkmate.",
        ["pill_must_capture"] = "Must capture",
        ["pill_max_capture"] = "Take the most",
        ["pill_optional_capture"] = "Captures optional",
        ["pill_flying"] = "Flying kings",
        ["pill_back"] = "Men capture back",
        ["pill_crown_stop"] = "Crowning ends the move",
        ["pill_crown_continue"] = "Crowned mid-capture",
        ["pill_crown_pass"] = "Crowned at the end",
        ["rules_button"] = "Rules",

        -- choosing a game
        ["setup_title"] = "Choose a game",
        ["setup_resume"] = "Pick up a saved game",
        ["setup_game"] = "Game",
        ["setup_opponent"] = "Opponent",
        ["setup_level"] = "Difficulty",
        ["setup_variant"] = "Rules",
        ["setup_rules"] = "How this game is played",
        ["setup_wager"] = "Wager",
        ["opponent_player"] = "A player",
        ["opponent_ai"] = "The AI",
        ["ai_seat_taken_tip"] = "Someone is sitting in the other chair: play them instead.",
        ["ai_off_tip"] = "Games against the AI are turned off here.",
        ["wager_explain"] = "Each player stakes this; the winner takes both. Blank for no wager. %s to %s.",
        ["custom_must"] = "Capturing is compulsory",
        ["custom_max"] = "Must take the most pieces",
        ["custom_flying"] = "Flying kings",
        ["custom_back"] = "Men capture backwards",
        ["custom_blocked"] = "A blocked player loses",
        ["custom_crown"] = "Crowned mid-capture",
        ["custom_first"] = "First move",
        ["custom_notation"] = "Notation",
        ["crown_stop"] = "Stops",
        ["crown_continue"] = "Goes on",
        ["crown_pass"] = "Passes",
        ["notation_numeric"] = "1-32",
        ["notation_algebraic"] = "a1-h8",
        ["start_ai"] = "Start the game",
        ["start_invite"] = "Invite %s",
        ["start_wait"] = "Wait for an opponent",
        ["setup_clock"] = "Clock",
        ["clock_none"] = "None",
        ["clock_custom"] = "Custom",
        ["clock_short"] = "%d+%d",
        ["clock_tip"] = "%d minutes each, %d seconds added after every move",
        ["clock_minutes"] = "Minutes each",
        ["clock_increment"] = "Seconds a move",
        ["clock_explain"] = "Each player has the minutes for the whole game, and the seconds are added after every move. It starts with the first move. Run out and you lose.",
        ["clock_explain_none"] = "No clock: take as long as you like.",
        ["clock_line"] = "Clock: %d minutes each, %d seconds added after every move. Run out and you lose.",

        -- waiting and invitations
        ["waiting_title"] = "Waiting",
        ["waiting_host"] = "%s is choosing a game. You will be asked to join.",
        ["invite_title"] = "A game is offered",
        ["invite_text"] = "%s invites you to a game of %s.",
        ["invite_resume"] = "This carries on a game you two saved earlier.",
        ["invite_wait_answer"] = "Waiting for %s to accept.",
        ["invite_wait_named"] = "Waiting for %s to sit in the other chair.",
        ["invite_wait_seat"] = "Waiting for someone to sit in the other chair.",
        ["wager_line"] = "Stake: %s each. The winner takes %s; a draw gives each their stake back. Standing up during the game loses it.",
        ["accept_stake"] = "Accept and stake %s",

        -- playing
        ["your_move_short"] = "Your move",
        ["their_move_short"] = "Their move",
        ["status_your_move"] = "Your move: click a piece, then where it goes.",
        ["status_pick_square"] = "Now click where it goes.",
        ["status_in_check"] = "Check! Your king must be made safe.",
        ["status_must_capture"] = "You must capture: the pieces that can take are ringed.",
        ["status_keep_jumping"] = "Keep jumping: click the next landing square. F or right-click takes the last jump back.",
        ["status_waiting"] = "%s to move.",
        ["status_ai_thinking"] = "%s is thinking...",
        ["status_sending"] = "...",
        ["status_draw_pending"] = "your draw offer is waiting",
        ["status_idle_claim"] = "%s has stopped playing. You can claim the win.",
        ["moves_title"] = "Moves",
        ["moves_none"] = "No moves yet.",
        ["captured_by"] = "Taken by %s",
        ["pieces_left"] = "%s: %d pieces (%d kings)",
        ["eval_label"] = "The AI's view",
        ["eval_mate"] = "Mate",
        ["btn_hint"] = "Hint",
        ["btn_draw"] = "Offer draw",
        ["btn_camera"] = "View",
        ["btn_resign"] = "Resign",
        ["btn_claim"] = "Claim the win",
        ["keys_chess"] = "Click a piece, then its square. G picks the square under the mouse, F lets go.",
        ["keys_checkers"] = "Click a piece, then each square it lands on. G picks the square under the mouse, F or right-click takes a jump back.",
        ["promote_title"] = "Promote to",
        ["piece_Q"] = "Queen",
        ["piece_R"] = "Rook",
        ["piece_B"] = "Bishop",
        ["piece_N"] = "Knight",
        ["resign_title"] = "Resign?",
        ["resign_text"] = "Your opponent wins the game.",
        ["resign_text_wager"] = "Your opponent wins the game and your %s stake.",
        ["draw_offer_text"] = "%s offers a draw.",
        ["draw_accept"] = "Agree to a draw",
        ["draw_decline"] = "Play on",

        -- the end of a game
        ["over_won"] = "You won",
        ["over_lost"] = "You lost",
        ["over_draw"] = "Draw",
        ["over_abandoned"] = "Game over, no result",
        ["over_saved"] = "Game saved",
        ["over_wager_won"] = "You take the pot: %s.",
        ["over_wager_lost"] = "You lose your %s stake.",
        ["over_wager_back"] = "Your %s stake is returned.",
        -- %s is the losing player, then the winner
        ["reason_checkmate"] = "%s is checkmated.",
        ["reason_resign"] = "%s resigned.",
        ["reason_left"] = "%s left the table.",
        ["reason_idle"] = "%s stopped playing, and the win was claimed.",
        ["reason_nopieces"] = "%s has no pieces left.",
        ["reason_blocked"] = "%s cannot move.",
        ["reason_stalemate"] = "Stalemate: the player to move has no legal move but is not in check.",
        ["reason_repetition"] = "The same position came up again and again.",
        ["reason_fifty"] = "Fifty moves each without a capture or a pawn move.",
        ["reason_noprogress"] = "Too long without a capture or a man moving.",
        ["reason_material"] = "Neither side has enough left to checkmate.",
        ["reason_agreement"] = "Both players agreed to a draw.",
        ["reason_death"] = "A player died at the table.",
        ["reason_admin"] = "An admin ended the game.",
        ["reason_timeout"] = "%s ran out of time.",
        -- %s is the player who ran out, then the other player
        ["reason_timeoutdraw"] = "%s ran out of time, but %s has too little left to checkmate.",
        ["reason_saved"] = "%s left the table. The game is saved, and either of you can pick it up from the start menu.",
        ["reason_short_checkmate"] = "checkmate",
        ["reason_short_resign"] = "resigned",
        ["reason_short_left"] = "left the table",
        ["reason_short_idle"] = "stopped playing",
        ["reason_short_nopieces"] = "no pieces left",
        ["reason_short_blocked"] = "no moves left",
        ["reason_short_stalemate"] = "stalemate",
        ["reason_short_repetition"] = "repetition",
        ["reason_short_fifty"] = "fifty-move rule",
        ["reason_short_noprogress"] = "no progress",
        ["reason_short_material"] = "not enough to mate",
        ["reason_short_agreement"] = "agreed",
        ["reason_short_death"] = "a player died",
        ["reason_short_admin"] = "ended by an admin",
        ["reason_short_timeout"] = "out of time",
        ["reason_short_timeoutdraw"] = "out of time, no mate possible",
        ["reason_short_stale"] = "left unfinished",
        ["reason_short_restart"] = "server restart",
        ["reason_short_saved"] = "saved",

        -- My record
        ["record_title"] = "My record",
        ["record_none"] = "No games here yet.",
        ["filter_all"] = "All",
        ["filter_hide_ai"] = "Hide games against the AI",
        ["tab_games"] = "Games",
        ["tab_summary"] = "Summary",
        ["tab_opponents"] = "Opponents",
        ["outcome_won"] = "Won",
        ["outcome_lost"] = "Lost",
        ["outcome_draw"] = "Draw",
        ["outcome_abandoned"] = "No result",
        ["outcome_unfinished"] = "Unfinished",
        ["page_prev"] = "Newer",
        ["page_next"] = "Older",
        ["page_of"] = "Page %d of %d",
        ["stat_wins"] = "Wins",
        ["stat_draws"] = "Draws",
        ["stat_losses"] = "Losses",
        ["stat_played"] = "Played",
        ["stat_vs_ai"] = "Against the AI",
        ["stat_unfinished"] = "Unfinished",
        ["win_rate"] = "Won %d%% of %d finished games",
        ["summary_note"] = "Only finished games count towards wins, draws and losses.",
        ["col_opponent"] = "Opponent",
        ["col_games"] = "Games",
        ["col_w"] = "W",
        ["col_d"] = "D",
        ["col_l"] = "L",
        ["review_partial"] = "This game was saved by an older version, and only part of it could be replayed.",

        -- ratings and the leaderboard
        ["tab_leaderboard"] = "Leaderboard",
        ["lb_rank"] = "#",
        ["lb_player"] = "Player",
        ["lb_rating"] = "Rating",
        ["lb_games"] = "Games",
        ["lb_none"] = "Nobody has played enough rated games yet.",
        ["lb_note"] = "Only games between two players are rated. Players appear here after %d rated games.",
        ["lb_mine"] = "Your %s rating: %d · rank %d of %d",
        ["lb_mine_unranked"] = "Your %s rating: %d · %d more rated games to appear here",
        ["lb_peak"] = "best %d",
        ["lb_off"] = "Ratings are turned off on this server.",
        ["stat_rating"] = "%s rating",
        ["rating_change"] = "%s rating",
        ["over_rating"] = "Rating %d → %d (%s)",
        ["provisional"] = "provisional",
        ["page_prev_lb"] = "Higher",
        ["page_next_lb"] = "Lower",
    },
}
