--[[
    poggy_emotes - the shipped emote catalogue

    This file is the emote library poggy_emotes ships with. It is CODE, not
    config: an update replaces it, so anything you change here is lost.

    To add your own emotes, or to change or hide one that ships here, use
    Config.CustomEmotes and Config.HiddenEmotes in config.lua. Those are
    yours, and an update never touches them.

    Every row has:
      name      what the player types after /e, and how the emote is saved
      label     the name shown in the menu
      category  one of the keys in Config.CategoryOrder
      gender    'any', 'male' or 'female' - who sees it in the menu
      kind      'scenario', 'kit' or 'anim' (below)
      gameProp  optional, true when the GAME hands the character a prop for
                this emote (the guitar, the bottle). It only marks the emote
                as a prop emote in the menu; the game does the rest.

    kind = 'scenario'   a world scenario the game plays for us
      scenario  the scenario name, e.g. 'WORLD_HUMAN_DRINKING'

    kind = 'kit'        one of the game's own built-in emotes
      hash      the emote's hash

    kind = 'anim'       an animation dictionary played on your character
      dict      the animation dictionary
      anim      the animation inside it
      speed     blend-in speed
      speedX    blend-out speed
      duration  how long it plays, in milliseconds, or -1 to hold
      flags     animation flags (1 loops, 2 holds the last frame, 49 upper body)
      prop      optional, the item held during the emote:
                  model     the prop model
                  bone      the bone it attaches to
                  x, y, z   position offset from that bone
                  rx,ry,rz  rotation offset, in degrees
]]

PoggyEmoteCatalogue = {
    { name = 'beer', label = 'Beer', category = 'consume', gender = 'any', kind = 'scenario', scenario = 'WORLD_HUMAN_DRINKING', gameProp = true },
    { name = 'beer2', label = 'Beer 2', category = 'consume', gender = 'any', kind = 'anim', dict = 'mech_dynamic@world_player_drinking@beer@male_a@chug_hi@loop', anim = 'chug_hi_loop', speed = 2.0, speedX = 2.0, duration = -1, flags = 0,
      prop = { model = 'p_bottleBeer01a', bone = 22798, x = 0.06, y = -0.08, z = -0.05, rx = -80.0, ry = 0.0, rz = -10.0 } },
    { name = 'beer3', label = 'Beer 3', category = 'consume', gender = 'male', kind = 'scenario', scenario = 'SC_PROP_STAND_REST_DRINK_MALES', gameProp = true },
    { name = 'champagne', label = 'Champagne', category = 'consume', gender = 'any', kind = 'scenario', scenario = 'WORLD_HUMAN_DRINK_CHAMPAGNE', gameProp = true },
    { name = 'cigar', label = 'Cigar', category = 'consume', gender = 'male', kind = 'scenario', scenario = 'WORLD_CAMP_DUTCH_SMOKE_CIGAR', gameProp = true },
    { name = 'coffee', label = 'Coffee', category = 'consume', gender = 'any', kind = 'scenario', scenario = 'WORLD_HUMAN_COFFEE_DRINK', gameProp = true },
    { name = 'drinkladle', label = 'Drink Ladle', category = 'consume', gender = 'any', kind = 'anim', dict = 'amb_rest_drunk@world_human_bucket_drink_ladle@ground@male_a@stand_enter', anim = 'enter_back_lf', speed = 2.0, speedX = 2.0, duration = -1, flags = 0,
      prop = { model = 'p_ladle04x', bone = 22798, x = 0.02, y = -0.03, z = 0.0, rx = -90.0, ry = 20.0, rz = -55.0 } },
    { name = 'flask', label = 'Flask', category = 'consume', gender = 'male', kind = 'scenario', scenario = 'WORLD_HUMAN_DRINK_FLASK', gameProp = true },
    { name = 'smoke', label = 'Smoke', category = 'consume', gender = 'male', kind = 'scenario', scenario = 'WORLD_HUMAN_SMOKE_MALE_A', gameProp = true },
    { name = 'smokef', label = 'Smoke', category = 'consume', gender = 'female', kind = 'scenario', scenario = 'WORLD_HUMAN_SMOKE_FEMALE_A', gameProp = true },
    { name = 'smoke3', label = 'Smoke (Nervous)', category = 'consume', gender = 'male', kind = 'scenario', scenario = 'WORLD_HUMAN_SMOKE_NERVOUS_STRESSED_MALE_B', gameProp = true },
    { name = 'smoke2', label = 'Smoke 2', category = 'consume', gender = 'male', kind = 'scenario', scenario = 'WORLD_HUMAN_SMOKE_CIGAR_MALE_A', gameProp = true },
    { name = 'smoke2f', label = 'Smoke 2', category = 'consume', gender = 'female', kind = 'scenario', scenario = 'WORLD_HUMAN_SMOKE_FEMALE_B', gameProp = true },
    { name = 'smoke3f', label = 'Smoke 3', category = 'consume', gender = 'female', kind = 'scenario', scenario = 'WORLD_HUMAN_SMOKE_FEMALE_C', gameProp = true },
    { name = 'stew', label = 'Stew', category = 'consume', gender = 'male', kind = 'scenario', scenario = 'WORLD_CAMP_SIT_GROUND_STEW', gameProp = true },
    { name = 'stew2', label = 'Stew 2', category = 'consume', gender = 'any', kind = 'anim', dict = 'amb_camp@prop_camp_cauldron_serve_stew@male_b@base', anim = 'base_trans_exit', speed = 2.0, speedX = 2.0, duration = -1, flags = 24 },
    { name = 'stew3', label = 'Stew 3', category = 'consume', gender = 'any', kind = 'anim', dict = 'mp_mech_inventory@stewpot_donation@male@action', anim = 'action_a', speed = 2.0, speedX = 2.0, duration = -1, flags = 0 },
    { name = 'taste', label = 'Taste', category = 'consume', gender = 'any', kind = 'anim', dict = 'amb_camp@world_camp_sit_ground_stew@eating@male_b@react_look@loop@generic', anim = 'react_look_front_loop', speed = 2.0, speedX = 2.0, duration = -1, flags = 1 },
    { name = 'taste2', label = 'Taste 2', category = 'consume', gender = 'any', kind = 'anim', dict = 'mech_dynamic@world_player_dynamic_kneel_ground@cook@grill1@eating@male_a@use_idles@idle_b', anim = 'idle_d', speed = 2.0, speedX = 2.0, duration = -1, flags = 0 },
    { name = 'boast', label = 'Boast', category = 'conversation', gender = 'any', kind = 'kit', hash = -1252070669 },
    { name = 'bow', label = 'Bow', category = 'conversation', gender = 'any', kind = 'kit', hash = -2121881035 },
    { name = 'bow2', label = 'Bow 2', category = 'conversation', gender = 'any', kind = 'kit', hash = -1801715172 },
    { name = 'checkout', label = 'Checkout', category = 'conversation', gender = 'any', kind = 'anim', dict = 'amb_misc@world_human_stare_stoic@male_a@react_look@enter@med', anim = 'react_look_right_enter', speed = 2.0, speedX = 2.0, duration = -1, flags = 0 },
    { name = 'checkout2', label = 'Checkout 2', category = 'conversation', gender = 'any', kind = 'anim', dict = 'amb_rest_lean@world_human_lean@railing@male_a@react_look@loop@generic', anim = 'react_look_backleft_loop', speed = 2.0, speedX = 2.0, duration = -1, flags = 0 },
    { name = 'checkout3', label = 'Checkout 3', category = 'conversation', gender = 'any', kind = 'anim', dict = 'amb_rest@world_human_smoking@female_a@react_look@enter@high', anim = 'react_look_left_enter', speed = 2.0, speedX = 2.0, duration = -1, flags = 0 },
    { name = 'checkout4', label = 'Checkout 4', category = 'conversation', gender = 'any', kind = 'anim', dict = 'amb_camp@world_camp_fire_sit_ground@recline@female_a@react_look@loop@generic', anim = 'react_look_front_loop', speed = 2.0, speedX = 2.0, duration = -1, flags = 1 },
    { name = 'checkout5', label = 'Checkout 5', category = 'conversation', gender = 'any', kind = 'anim', dict = 'amb_rest_lean@world_human_lean@railing@right@female_a@react_look@loop@generic', anim = 'react_look_right_loop', speed = 2.0, speedX = 2.0, duration = -1, flags = 0 },
    { name = 'checkout6', label = 'Checkout 6', category = 'conversation', gender = 'any', kind = 'anim', dict = 'amb_rest_lean@world_human_lean@railing@smoking@male_d@react_look@loop@generic', anim = 'react_look_front_loop', speed = 2.0, speedX = 2.0, duration = -1, flags = 0 },
    { name = 'converse', label = 'Converse', category = 'conversation', gender = 'any', kind = 'anim', dict = 'mech_loco_m@generic@converse@unarmed@idle', anim = 'idle_turn_l_-90', speed = 2.0, speedX = 2.0, duration = -1, flags = 0 },
    { name = 'converse2', label = 'Converse 2', category = 'conversation', gender = 'any', kind = 'anim', dict = 'mech_loco_m@generic@converse@unarmed@idle', anim = 'idle_turn_r_90', speed = 2.0, speedX = 2.0, duration = -1, flags = 0 },
    { name = 'converse3', label = 'Converse 3', category = 'conversation', gender = 'any', kind = 'anim', dict = 'mech_loco_m@generic@converse@unarmed@walk_slow@backward', anim = 'move', speed = 2.0, speedX = 2.0, duration = 1500, flags = 0 },
    { name = 'dropitem', label = 'Drop Item', category = 'conversation', gender = 'any', kind = 'anim', dict = 'mech_pickup@dyn_bundle@drop', anim = 'drop', speed = 2.0, speedX = 2.0, duration = -1, flags = 0 },
    { name = 'explain', label = 'Explain', category = 'conversation', gender = 'any', kind = 'anim', dict = 'script_common@gestures@unapproved@proto', anim = 'explain_both_hands_intro', speed = 2.0, speedX = 2.0, duration = -1, flags = 0 },
    { name = 'explain2', label = 'Explain 2', category = 'conversation', gender = 'any', kind = 'anim', dict = 'script_story@odr1@ig@ig2_dutch_explains_plan', anim = 'ig2_action_dutch', speed = 2.0, speedX = 2.0, duration = -1, flags = 24 },
    { name = 'facepalm', label = 'Facepalm', category = 'conversation', gender = 'any', kind = 'kit', hash = -1384541404 },
    { name = 'facepalm2', label = 'Facepalm 2', category = 'conversation', gender = 'any', kind = 'anim', dict = 'script_mp@emotes@facepalm@male@unarmed@upper', anim = 'loop', speed = 2.0, speedX = 2.0, duration = -1, flags = 1 },
    { name = 'giveitem', label = 'Give Item', category = 'conversation', gender = 'any', kind = 'anim', dict = 'script_common@mth_generic_enters@give_item_satchel@lhand@generic@in_place', anim = 'enter_lf', speed = 2.0, speedX = 2.0, duration = -1, flags = 0 },
    { name = 'handout', label = 'Handout', category = 'conversation', gender = 'any', kind = 'anim', dict = 'amb_camp@world_camp_bowl_put_down_washbasin@male_b@base', anim = 'base', speed = 2.0, speedX = 2.0, duration = 3000, flags = 1 },
    { name = 'handout2', label = 'Handout 2', category = 'conversation', gender = 'any', kind = 'anim', dict = 'script_common@tailor_shop', anim = 'handout_linger_long', speed = 2.0, speedX = 2.0, duration = -1, flags = 0 },
    { name = 'heyyou', label = 'Hey You', category = 'conversation', gender = 'any', kind = 'kit', hash = 831975651 },
    { name = 'hush', label = 'Hush', category = 'conversation', gender = 'any', kind = 'kit', hash = -1644757697 },
    { name = 'no', label = 'No', category = 'conversation', gender = 'any', kind = 'kit', hash = -653113914 },
    { name = 'noway', label = 'No Way', category = 'conversation', gender = 'any', kind = 'anim', dict = 'script_common@gestures@unapproved', anim = 'gesture_no_way', speed = 2.0, speedX = 2.0, duration = -1, flags = 0 },
    { name = 'nod', label = 'Nod', category = 'conversation', gender = 'any', kind = 'kit', hash = -822629770 },
    { name = 'provoke', label = 'Provoke', category = 'conversation', gender = 'any', kind = 'kit', hash = 1533402397 },
    { name = 'smh', label = 'SMH', category = 'conversation', gender = 'any', kind = 'anim', dict = 'mech_loco_m@character@arthur@fidgets@core@normal@deadeye@unarmed', anim = 'head_shake_02', speed = 2.0, speedX = 2.0, duration = -1, flags = 24 },
    { name = 'thanks', label = 'Thanks', category = 'conversation', gender = 'any', kind = 'kit', hash = 2144049308 },
    { name = 'thanksfemale', label = 'Thanks (Female)', category = 'conversation', gender = 'any', kind = 'anim', dict = 'script_re@wealthy_couple', anim = 'thanks_woman', speed = 8.0, speedX = 3.0, duration = -1, flags = 24 },
    { name = 'thanksfemale2', label = 'Thanks (Female) 2', category = 'conversation', gender = 'any', kind = 'anim', dict = 'script_re@wealthy_couple', anim = 'thanks_v2_female_woman', speed = 8.0, speedX = 3.0, duration = -1, flags = 24 },
    { name = 'thanksmale', label = 'Thanks (Male)', category = 'conversation', gender = 'any', kind = 'anim', dict = 'script_re@wealthy_couple', anim = 'thanks_man', speed = 8.0, speedX = 3.0, duration = -1, flags = 24 },
    { name = 'thanksmale2', label = 'Thanks (Male) 2', category = 'conversation', gender = 'any', kind = 'anim', dict = 'script_re@wealthy_couple', anim = 'thanks_v2_man', speed = 8.0, speedX = 3.0, duration = -1, flags = 24 },
    { name = 'tough', label = 'Tough', category = 'conversation', gender = 'any', kind = 'kit', hash = 1879954891 },
    { name = 'upyours', label = 'Up Yours', category = 'conversation', gender = 'any', kind = 'kit', hash = 354512356 },
    { name = 'what', label = 'What', category = 'conversation', gender = 'any', kind = 'anim', dict = 'script_common@gestures@unapproved', anim = 'gesture_what_soft', speed = 2.0, speedX = 2.0, duration = -1, flags = 24 },
    { name = 'whome', label = 'Who Me?', category = 'conversation', gender = 'any', kind = 'kit', hash = 329631369 },
    { name = 'cancan', label = 'Can Can', category = 'dance', gender = 'any', kind = 'anim', dict = 'script_shows@cancandance@p2', anim = 'cancandance_p2_fem3', speed = 2.0, speedX = 2.0, duration = -1, flags = 0 },
    { name = 'cancan2', label = 'Can Can 2', category = 'dance', gender = 'any', kind = 'anim', dict = 'script_shows@cancandance@p1', anim = 'cancandance_fem3', speed = 2.0, speedX = 2.0, duration = -1, flags = 0 },
    { name = 'dance1', label = 'Dance 1', category = 'dance', gender = 'any', kind = 'anim', dict = 'amb_misc@world_human_drunk_dancing@male@male_b@idle_a', anim = 'idle_b', speed = 2.0, speedX = 2.0, duration = -1, flags = 0 },
    { name = 'dance10', label = 'Dance 10', category = 'dance', gender = 'any', kind = 'kit', hash = -293533575 },
    { name = 'dance11', label = 'Dance 11', category = 'dance', gender = 'any', kind = 'kit', hash = -256960614 },
    { name = 'dance12', label = 'Dance 12', category = 'dance', gender = 'any', kind = 'kit', hash = -632925771 },
    { name = 'dance13', label = 'Dance 13', category = 'dance', gender = 'any', kind = 'kit', hash = -184244429 },
    { name = 'dance14', label = 'Dance 14', category = 'dance', gender = 'any', kind = 'kit', hash = -19706765 },
    { name = 'dance15', label = 'Dance 15', category = 'dance', gender = 'any', kind = 'kit', hash = -1790393337 },
    { name = 'dance16', label = 'Dance 16', category = 'dance', gender = 'any', kind = 'kit', hash = 1043523184 },
    { name = 'dance17', label = 'Dance 17', category = 'dance', gender = 'any', kind = 'kit', hash = 1874713704 },
    { name = 'dance18', label = 'Dance 18', category = 'dance', gender = 'any', kind = 'kit', hash = -2072898350 },
    { name = 'dance19', label = 'Dance 19', category = 'dance', gender = 'any', kind = 'kit', hash = -808997190 },
    { name = 'dance2', label = 'Dance 2', category = 'dance', gender = 'any', kind = 'anim', dict = 'script_mp@emotes@dance@drunk@b@male@unarmed@full', anim = 'fullbody', speed = 2.0, speedX = 2.0, duration = -1, flags = 0 },
    { name = 'dance20', label = 'Dance 20', category = 'dance', gender = 'any', kind = 'kit', hash = 217596073 },
    { name = 'dance21', label = 'Dance 21', category = 'dance', gender = 'any', kind = 'kit', hash = 1140268200 },
    { name = 'dance3', label = 'Dance 3', category = 'dance', gender = 'any', kind = 'anim', dict = 'script_mp@emotes@dance@confident@b@male@unarmed@full', anim = 'fullbody', speed = 2.0, speedX = 2.0, duration = -1, flags = 0 },
    { name = 'dance4', label = 'Dance 4', category = 'dance', gender = 'any', kind = 'anim', dict = 'script_mp@emotes@dance@wild@b@male@unarmed@full', anim = 'fullbody', speed = 2.0, speedX = 2.0, duration = -1, flags = 0 },
    { name = 'dance5', label = 'Dance 5', category = 'dance', gender = 'any', kind = 'anim', dict = 'script_mp@emotes@dance@drunk@a@male@unarmed@full', anim = 'fullbody', speed = 2.0, speedX = 2.0, duration = -1, flags = 0 },
    { name = 'dance6', label = 'Dance 6', category = 'dance', gender = 'any', kind = 'anim', dict = 'script_mp@emotes@dance@old@a@male@unarmed@full', anim = 'fullbody', speed = 2.0, speedX = 2.0, duration = -1, flags = 0 },
    { name = 'dance7', label = 'Dance 7', category = 'dance', gender = 'any', kind = 'anim', dict = 'script_mp@emotes@dance@confident@b@male@unarmed@full', anim = 'fullbody', speed = 2.0, speedX = 2.0, duration = -1, flags = 0 },
    { name = 'dance8', label = 'Dance 8', category = 'dance', gender = 'any', kind = 'anim', dict = 'script_mp@emotes@dance@carefree@a@male@unarmed@full', anim = 'fullbody', speed = 2.0, speedX = 2.0, duration = -1, flags = 0 },
    { name = 'dance9', label = 'Dance 9', category = 'dance', gender = 'any', kind = 'anim', dict = 'script_mp@emotes@dance@awkward@a@male@unarmed@full', anim = 'fullbody', speed = 2.0, speedX = 2.0, duration = -1, flags = 0 },
    { name = 'firedance', label = 'Fire Dance', category = 'dance', gender = 'any', kind = 'anim', dict = 'script_shows@firedancer@act3_p1', anim = 'dance', speed = 2.0, speedX = 2.0, duration = -1, flags = 0,
      prop = { model = 'p_torch01x', bone = 22798, x = 0.06, y = -0.08, z = -0.05, rx = -80.0, ry = 20.0, rz = -15.0 } },
    { name = 'jig', label = 'Jig', category = 'dance', gender = 'any', kind = 'anim', dict = 'script_mp@emotes@prospector_jig@male@unarmed@full', anim = 'fullbody', speed = 2.0, speedX = 2.0, duration = -1, flags = 0 },
    { name = 'snakedance', label = 'Snake Dance', category = 'dance', gender = 'any', kind = 'anim', dict = 'script_shows@snakedancer@act1_p1', anim = 'dance_dancer', speed = 2.0, speedX = 2.0, duration = -1, flags = 0 },
    { name = 'snakedance2', label = 'Snake Dance 2', category = 'dance', gender = 'any', kind = 'anim', dict = 'script_shows@snakedancer@act2_p1', anim = 'dance_dancer', speed = 2.0, speedX = 2.0, duration = -1, flags = 0 },
    { name = 'sworddance', label = 'Sword Dance', category = 'dance', gender = 'any', kind = 'anim', dict = 'script_shows@sworddance@act3_p1', anim = 'dancer_sworddance', speed = 2.0, speedX = 2.0, duration = -1, flags = 0,
      prop = { model = 'p_sword01x', bone = 22798, x = 0.06, y = -0.08, z = -0.05, rx = -80.0, ry = 20.0, rz = -15.0 } },
    { name = 'aim', label = 'Aim', category = 'gestures', gender = 'any', kind = 'kit', hash = 988397866 },
    { name = 'aim2', label = 'Aim 2', category = 'gestures', gender = 'any', kind = 'anim', dict = 'ai_combat@aim_sweeps@cowboy@stance_a@low_intensity@upperbody@1h', anim = 'aim_med_r90', speed = 2.0, speedX = 2.0, duration = -1, flags = 0 },
    { name = 'bangchest', label = 'Bang Chest', category = 'gestures', gender = 'any', kind = 'kit', hash = 1897736735 },
    { name = 'beg', label = 'Beg', category = 'gestures', gender = 'any', kind = 'anim', dict = 'amb_misc@world_human_begging_mother@female_a@react_begging', anim = 'react_begging_frontleft', speed = 2.0, speedX = 2.0, duration = -1, flags = 1 },
    { name = 'birds', label = 'Birds', category = 'gestures', gender = 'any', kind = 'anim', dict = 'script_re@sharp_shooter@alt_intros_birds', anim = 'bird_rules_shooter', speed = 8.0, speedX = 3.0, duration = -1, flags = 0 },
    { name = 'blowkiss', label = 'Blowkiss', category = 'gestures', gender = 'any', kind = 'kit', hash = 1927505461 },
    { name = 'boohoo', label = 'Boohoo', category = 'gestures', gender = 'any', kind = 'kit', hash = 246916594 },
    { name = 'callout', label = 'Callout', category = 'gestures', gender = 'any', kind = 'kit', hash = -2104721573 },
    { name = 'cards', label = 'Cards', category = 'gestures', gender = 'any', kind = 'kit', hash = -843470756, gameProp = true },
    { name = 'chicken', label = 'Chicken', category = 'gestures', gender = 'any', kind = 'kit', hash = 1825177171 },
    { name = 'clap', label = 'Clap', category = 'gestures', gender = 'any', kind = 'kit', hash = -934299978 },
    { name = 'clap2', label = 'Clap 2', category = 'gestures', gender = 'any', kind = 'kit', hash = 1023735814 },
    { name = 'clap3', label = 'Clap 3', category = 'gestures', gender = 'any', kind = 'kit', hash = -221241824 },
    { name = 'coin', label = 'Coin', category = 'gestures', gender = 'any', kind = 'kit', hash = -667707842, gameProp = true },
    { name = 'concerned', label = 'Concerned', category = 'gestures', gender = 'any', kind = 'anim', dict = 'script_story@ntv3@ig@ig12_nativewapitireaction_p4', anim = 'concerned_01_native', speed = 2.0, speedX = 2.0, duration = -1, flags = 0 },
    { name = 'concerned2', label = 'Concerned 2', category = 'gestures', gender = 'any', kind = 'anim', dict = 'script_story@ntv3@ig@ig12_nativewapitireaction_p4', anim = 'concerned_frail_02_native', speed = 2.0, speedX = 2.0, duration = -1, flags = 0 },
    { name = 'concerned3', label = 'Concerned 3', category = 'gestures', gender = 'any', kind = 'anim', dict = 'script_story@ntv3@ig@ig12_nativewapitireaction_p3', anim = 'concerned_04_female_native_female', speed = 2.0, speedX = 2.0, duration = -1, flags = 0 },
    { name = 'cower', label = 'Cower', category = 'gestures', gender = 'any', kind = 'anim', dict = 'mech_loco_m@generic@emotion@unarmed@cower@known@idle', anim = 'idle', speed = 2.0, speedX = 2.0, duration = -1, flags = 1 },
    { name = 'cower2', label = 'Cower 2', category = 'gestures', gender = 'any', kind = 'anim', dict = 'mech_loco_m@generic@emotion@unarmed@cower@unknown@idle', anim = 'idle_intro', speed = 2.0, speedX = 2.0, duration = -1, flags = 1 },
    { name = 'cower3', label = 'Cower 3', category = 'gestures', gender = 'any', kind = 'anim', dict = 'mech_loco_m@generic@emotion@unarmed@cower@known@idle@fidget', anim = 'fidget_f', speed = 2.0, speedX = 2.0, duration = -1, flags = 1 },
    { name = 'cry', label = 'Cry', category = 'gestures', gender = 'any', kind = 'anim', dict = 'script_common@other@unapproved', anim = 'cry_loop', speed = 2.0, speedX = 2.0, duration = -1, flags = 1 },
    { name = 'dustoff', label = 'Dust Off', category = 'gestures', gender = 'any', kind = 'anim', dict = 'ai_react@shake_it_off', anim = 'dustoff', speed = 2.0, speedX = 2.0, duration = -1, flags = 0 },
    { name = 'fishing', label = 'Fishing', category = 'gestures', gender = 'male', kind = 'scenario', scenario = 'WORLD_HUMAN_STAND_FISHING', gameProp = true },
    { name = 'fistpump', label = 'Fist Pump', category = 'gestures', gender = 'any', kind = 'kit', hash = -402959 },
    { name = 'flex', label = 'Flex', category = 'gestures', gender = 'any', kind = 'kit', hash = -773960361 },
    { name = 'flinch', label = 'Flinch', category = 'gestures', gender = 'any', kind = 'anim', dict = 'mech_cover@flinch@arthur@unarmed@base@low@right@no_lean', anim = 'flinch_c', speed = 2.0, speedX = 2.0, duration = -1, flags = 1 },
    { name = 'flipoff', label = 'Flip Off', category = 'gestures', gender = 'any', kind = 'kit', hash = 969312568 },
    { name = 'followme', label = 'Follow Me', category = 'gestures', gender = 'any', kind = 'kit', hash = 1115379199 },
    { name = 'gentletip', label = 'Gentle Tip', category = 'gestures', gender = 'any', kind = 'anim', dict = 'mech_loco_m@character@dutch@fancy@unarmed@idle@_variations', anim = 'idle_b', speed = 2.0, speedX = 2.0, duration = -1, flags = 28 },
    { name = 'guy', label = 'Guy', category = 'gestures', gender = 'any', kind = 'kit', hash = 593885605 },
    { name = 'handsup', label = 'Hands Up', category = 'gestures', gender = 'any', kind = 'anim', dict = 'script_proc@robberies@shop@rhodes@gunsmith@inside_upstairs', anim = 'handsup_register_owner', speed = 1.5, speedX = -1.5, duration = -1, flags = 31 },
    { name = 'handsup2', label = 'Hands Up 2', category = 'gestures', gender = 'any', kind = 'anim', dict = 'script_proc@robberies@homestead@lonnies_shack@deception', anim = 'hands_up_loop', speed = 2.0, speedX = 2.0, duration = -1, flags = 1 },
    { name = 'handshake', label = 'Handshake', category = 'gestures', gender = 'any', kind = 'kit', hash = 1785080714 },
    { name = 'happytoseeyou', label = 'Happy to See You', category = 'gestures', gender = 'any', kind = 'kit', hash = 523585988 },
    { name = 'hatflick', label = 'Hat Flick', category = 'gestures', gender = 'any', kind = 'kit', hash = -511010399 },
    { name = 'hattip', label = 'Hat Tip', category = 'gestures', gender = 'any', kind = 'kit', hash = -1457020913 },
    { name = 'heckle', label = 'Heckle', category = 'gestures', gender = 'any', kind = 'anim', dict = 'script_rc@bnp1@ig@rsc2_ig3_heckler_gestures', anim = 'female_a_upper_aggresive_a_female^1', speed = 8.0, speedX = 3.0, duration = -1, flags = 24 },
    { name = 'heckle2', label = 'Heckle 2', category = 'gestures', gender = 'any', kind = 'anim', dict = 'script_rc@bnp1@ig@rsc2_ig3_heckler_gestures', anim = 'male_a_upper_aggresive_a_male^3', speed = 8.0, speedX = 3.0, duration = -1, flags = 24 },
    { name = 'hissyfit', label = 'Hissy Fit', category = 'gestures', gender = 'any', kind = 'kit', hash = 796723886 },
    { name = 'howdareyou', label = 'How Dare You?', category = 'gestures', gender = 'any', kind = 'kit', hash = 1802342943 },
    { name = 'hypnosis', label = 'Hypnosis', category = 'gestures', gender = 'any', kind = 'kit', hash = -869481556 },
    { name = 'indicate2', label = 'Indicate', category = 'gestures', gender = 'any', kind = 'kit', hash = 7918540 },
    { name = 'knock', label = 'Knock', category = 'gestures', gender = 'male', kind = 'anim', dict = 'amb_misc@world_human_door_knock@male_a@idle_c', anim = 'idle_g', speed = 2.0, speedX = 2.0, duration = -1, flags = 1 },
    { name = 'knock2', label = 'Knock 2', category = 'gestures', gender = 'female', kind = 'anim', dict = 'amb_misc@world_human_door_knock@male_a@idle_c', anim = 'idle_h', speed = 2.0, speedX = 2.0, duration = -1, flags = 1 },
    { name = 'lefthattip', label = 'Left Hat Tip', category = 'gestures', gender = 'any', kind = 'anim', dict = 'mech_loco_m@character@arthur@fidgets@hat@normal@unarmed@normal@left_hand', anim = 'hat_lhand_b', speed = 2.0, speedX = 2.0, duration = -1, flags = 28 },
    { name = 'letscraft', label = 'Lets Craft', category = 'gestures', gender = 'any', kind = 'kit', hash = -415456998 },
    { name = 'letsgo', label = 'Lets Go', category = 'gestures', gender = 'any', kind = 'kit', hash = 1593752891 },
    { name = 'lookfar', label = 'Look Far', category = 'gestures', gender = 'any', kind = 'kit', hash = 935157006 },
    { name = 'mercy', label = 'Mercy', category = 'gestures', gender = 'any', kind = 'kit', hash = 164860528 },
    { name = 'mourning', label = 'Mourning', category = 'gestures', gender = 'any', kind = 'scenario', scenario = 'WORLD_HUMAN_GRAVE_MOURNING' },
    { name = 'mourning2', label = 'Mourning 2', category = 'gestures', gender = 'male', kind = 'scenario', scenario = 'SC_WORLD_STAND_MOURNING_MALE_A' },
    { name = 'mourningkneel', label = 'Mourning Kneel', category = 'gestures', gender = 'any', kind = 'scenario', scenario = 'WORLD_HUMAN_GRAVE_MOURNING_KNEEL' },
    { name = 'overthere', label = 'Over There', category = 'gestures', gender = 'any', kind = 'anim', dict = 'ai_gestures@gen_female@standing@speaker@lt_hand', anim = 'neutral_point_r_003', speed = 2.0, speedX = 2.0, duration = -1, flags = 1 },
    { name = 'overthere2', label = 'Over There 2', category = 'gestures', gender = 'male', kind = 'scenario', scenario = 'WORLD_PLAYER_LOOKAT_POINT' },
    { name = 'pocketwatch', label = 'Pocketwatch', category = 'gestures', gender = 'any', kind = 'kit', hash = -380388425, gameProp = true },
    { name = 'point', label = 'Point', category = 'gestures', gender = 'any', kind = 'kit', hash = 486225122 },
    { name = 'point2', label = 'Point 2', category = 'gestures', gender = 'any', kind = 'anim', dict = 'ai_gestures@gen_male@standing@speaker@lt_hand', anim = 'angry_point_r_001', speed = 2.0, speedX = 2.0, duration = -1, flags = 0 },
    { name = 'pointlaugh', label = 'Point Laugh', category = 'gestures', gender = 'any', kind = 'kit', hash = 803206066 },
    { name = 'pointlaugh2', label = 'Point Laugh 2', category = 'gestures', gender = 'any', kind = 'kit', hash = 296809845 },
    { name = 'posseup', label = 'Posse Up', category = 'gestures', gender = 'any', kind = 'kit', hash = 474409519 },
    { name = 'pray', label = 'Pray', category = 'gestures', gender = 'any', kind = 'kit', hash = 844130790 },
    { name = 'scheme', label = 'Scheme', category = 'gestures', gender = 'any', kind = 'kit', hash = 589481092 },
    { name = 'shoothip', label = 'Shoot Hip', category = 'gestures', gender = 'any', kind = 'kit', hash = -1639456476 },
    { name = 'shootsky', label = 'Shoot Sky', category = 'gestures', gender = 'any', kind = 'kit', hash = 1939251934 },
    { name = 'shot', label = 'Shot', category = 'gestures', gender = 'any', kind = 'kit', hash = -110352861 },
    { name = 'snook', label = 'Snook', category = 'gestures', gender = 'any', kind = 'kit', hash = 1379772889 },
    { name = 'snot', label = 'Snot', category = 'gestures', gender = 'any', kind = 'kit', hash = 1695841551 },
    { name = 'sob', label = 'Sob', category = 'gestures', gender = 'any', kind = 'kit', hash = 81347960 },
    { name = 'spit', label = 'Spit', category = 'gestures', gender = 'any', kind = 'kit', hash = -2106738342 },
    { name = 'spit2', label = 'Spit 2', category = 'gestures', gender = 'any', kind = 'anim', dict = 'ai_gestures@gen_male@standing@silent@script@rt_hand@prop_rt', anim = 'silent_neutral_spit_f_001', speed = 2.0, speedX = 2.0, duration = -1, flags = 0 },
    { name = 'spit3', label = 'Spit 3', category = 'gestures', gender = 'any', kind = 'anim', dict = 'ai_gestures@gen_male@standing@silent@script@rt_hand@prop_rt', anim = 'silent_aggressive_spit_f_001', speed = 2.0, speedX = 2.0, duration = -1, flags = 0 },
    { name = 'stink', label = 'Stink', category = 'gestures', gender = 'any', kind = 'kit', hash = -166523388 },
    { name = 'stomp', label = 'Stomp', category = 'gestures', gender = 'any', kind = 'anim', dict = 'amb_camp@world_camp_fire@stomp@male_c@wip_base', anim = 'wip_base', speed = 2.0, speedX = 2.0, duration = -1, flags = 0 },
    { name = 'stomp2', label = 'Stomp 2', category = 'gestures', gender = 'any', kind = 'anim', dict = 'mech_melee@blunt@_male@_ambient@_healthy@_noncombat', anim = 'attack_kick_stomp_rightside_dist_med_v1', speed = 2.0, speedX = 2.0, duration = -1, flags = 0 },
    { name = 'stomp3', label = 'Stomp 3', category = 'gestures', gender = 'any', kind = 'anim', dict = 'mech_melee@lasso@_male@_ambient@_healthy@_noncombat', anim = 'attack_kick_stomp_rightside_dist_near_v1', speed = 2.0, speedX = 2.0, duration = -1, flags = 0 },
    { name = 'stomp4', label = 'Stomp 4', category = 'gestures', gender = 'any', kind = 'anim', dict = 'mech_melee@rifle@_male@_ambient@_healthy@_noncombat', anim = 'attack_kick_stomp_leftside_dist_near_v1', speed = 2.0, speedX = 2.0, duration = -1, flags = 0 },
    { name = 'stophere', label = 'Stop Here', category = 'gestures', gender = 'any', kind = 'kit', hash = -1691237868 },
    { name = 'tada', label = 'Tada', category = 'gestures', gender = 'any', kind = 'kit', hash = -462132925 },
    { name = 'throatslit', label = 'Throat Slit', category = 'gestures', gender = 'any', kind = 'kit', hash = 1256841324 },
    { name = 'thumbsdown', label = 'Thumbs Down', category = 'gestures', gender = 'any', kind = 'kit', hash = 1509171361 },
    { name = 'thumbsup', label = 'Thumbs Up', category = 'gestures', gender = 'any', kind = 'kit', hash = 425751659 },
    { name = 'tiedup', label = 'Tied Up', category = 'gestures', gender = 'any', kind = 'anim', dict = 'amb_camp@world_camp_kieran_tied_up@cold@male_b@react_look@loop@generic', anim = 'react_look_front_loop', speed = 2.0, speedX = 2.0, duration = -1, flags = 1 },
    { name = 'tiedup2', label = 'Tied Up 2', category = 'gestures', gender = 'any', kind = 'anim', dict = 'amb_camp@world_camp_kieran_tied_up_tree@sit_ground@male_a@base', anim = 'base', speed = 2.0, speedX = 2.0, duration = -1, flags = 1 },
    { name = 'trumpet', label = 'Trumpet', category = 'gestures', gender = 'male', kind = 'scenario', scenario = 'WORLD_HUMAN_TRUMPET', gameProp = true },
    { name = 'warcry', label = 'War Cry', category = 'gestures', gender = 'any', kind = 'kit', hash = 987239450 },
    { name = 'washface', label = 'Wash Face', category = 'gestures', gender = 'any', kind = 'scenario', scenario = 'PROP_PLAYER_WASH_FACE_BARREL' },
    { name = 'washhands', label = 'Wash Hands', category = 'gestures', gender = 'any', kind = 'scenario', scenario = 'WORLD_HUMAN_WASH_FACE_BUCKET_GROUND_NO_BUCKET' },
    { name = 'watchyou', label = 'Watch You', category = 'gestures', gender = 'any', kind = 'kit', hash = -553424129 },
    { name = 'wave', label = 'Wave', category = 'gestures', gender = 'any', kind = 'kit', hash = 901097731 },
    { name = 'wave2', label = 'Wave 2', category = 'gestures', gender = 'any', kind = 'kit', hash = -1551032732 },
    { name = 'wave3', label = 'Wave 3', category = 'gestures', gender = 'any', kind = 'kit', hash = -339257980 },
    { name = 'wave4', label = 'Wave 4', category = 'gestures', gender = 'any', kind = 'anim', dict = 'script_re@herbalistcamp@leadin@rc1', anim = 'waveover_r_herbalist', speed = 2.0, speedX = 2.0, duration = -1, flags = 0 },
    { name = 'wipeeyes', label = 'Wipe Eyes', category = 'gestures', gender = 'any', kind = 'anim', dict = 'mech_loco_m@character@arthur@fidgets@core@normal@deadeye@unarmed', anim = 'wipe_eyes_lhand', speed = 2.0, speedX = 2.0, duration = -1, flags = 0 },
    { name = 'worship', label = 'Worship', category = 'gestures', gender = 'any', kind = 'anim', dict = 'script_special_ped@pdsnw_sun_worshipper@ig@ig_1', anim = 'ig1_pdsnw_wnt_heywhatyoudoin_ig_sunworshipper', speed = 2.0, speedX = 2.0, duration = -1, flags = 0 },
    { name = 'yeehaw', label = 'Yeehaw', category = 'gestures', gender = 'any', kind = 'kit', hash = 445839715 },
    { name = 'anticipate', label = 'Anticipate', category = 'idle', gender = 'male', kind = 'scenario', scenario = 'SC_WORLD_HUMAN_STAND_ANTICIPATE' },
    { name = 'badass', label = 'Badass', category = 'idle', gender = 'male', kind = 'scenario', scenario = 'WORLD_HUMAN_BADASS' },
    { name = 'cold', label = 'Cold', category = 'idle', gender = 'any', kind = 'anim', dict = 'script_re@lost_man', anim = 'idle', speed = 2.0, speedX = 2.0, duration = -1, flags = 1 },
    { name = 'crossarms', label = 'Cross Arms', category = 'idle', gender = 'any', kind = 'anim', dict = 'script_respawn@looping@hybrid@generic@unarmed@lean_left_arms_crossed@a@idles', anim = 'respawn_idle_3', speed = 2.0, speedX = 2.0, duration = -1, flags = 1 },
    { name = 'crossarms2', label = 'Cross Arms 2', category = 'idle', gender = 'any', kind = 'anim', dict = 'script_respawn@looping@hybrid@generic@unarmed@lean_left_arms_crossed@a', anim = 'respawn_loop', speed = 2.0, speedX = 2.0, duration = -1, flags = 1 },
    { name = 'drunk', label = 'Drunk', category = 'idle', gender = 'any', kind = 'anim', dict = 'script_re@crashed_wagon', anim = 'male_drunk_action', speed = 2.0, speedX = 2.0, duration = -1, flags = 1 },
    { name = 'fan', label = 'Fan', category = 'idle', gender = 'female', kind = 'scenario', scenario = 'WORLD_HUMAN_FAN', gameProp = true },
    { name = 'fan2', label = 'Fan 2', category = 'idle', gender = 'male', kind = 'scenario', scenario = 'WORLD_HUMAN_FAN_MALE_SAL1', gameProp = true },
    { name = 'fire', label = 'Fire', category = 'idle', gender = 'any', kind = 'scenario', scenario = 'WORLD_HUMAN_FIRE_STAND' },
    { name = 'guard', label = 'Guard', category = 'idle', gender = 'any', kind = 'anim', dict = 'amb_wander@code_human_guard_wander@lazy@male_b@idle_a', anim = 'idle_c', speed = 2.0, speedX = 2.0, duration = -1, flags = 1 },
    { name = 'handcounter2', label = 'Hand Counter 2', category = 'idle', gender = 'any', kind = 'scenario', scenario = 'WORLD_HUMAN_SHOPKEEPER_CATALOG', gameProp = true },
    { name = 'idle', label = 'Idle', category = 'idle', gender = 'male', kind = 'anim', dict = 'script_story@mob5@ig@ig_5_guardbackyard', anim = 'base_guard', speed = 2.0, speedX = 2.0, duration = -1, flags = 1 },
    { name = 'idle2', label = 'Idle 2', category = 'idle', gender = 'any', kind = 'scenario', scenario = 'MP_LOBBY_SCENARIO_07' },
    { name = 'idle3', label = 'Idle 3', category = 'idle', gender = 'any', kind = 'scenario', scenario = 'MP_LOBBY_SCENARIO_04' },
    { name = 'idle4', label = 'Idle 4', category = 'idle', gender = 'any', kind = 'scenario', scenario = 'MP_LOBBY_STANDING_G' },
    { name = 'idle5', label = 'Idle 5', category = 'idle', gender = 'any', kind = 'scenario', scenario = 'MP_LOBBY_SCENARIO_11' },
    { name = 'idle6', label = 'Idle 6', category = 'idle', gender = 'any', kind = 'scenario', scenario = 'MP_LOBBY_STANDING_F' },
    { name = 'idle7', label = 'Idle 7', category = 'idle', gender = 'any', kind = 'scenario', scenario = 'MP_LOBBY_SCENARIO_02' },
    { name = 'idle8', label = 'Idle 8', category = 'idle', gender = 'any', kind = 'scenario', scenario = 'MP_LOBBY_SCENARIO_05' },
    { name = 'impatient', label = 'Impatient', category = 'idle', gender = 'male', kind = 'scenario', scenario = 'WORLD_HUMAN_WAITING_IMPATIENT' },
    { name = 'lean2', label = 'Lean 2', category = 'idle', gender = 'male', kind = 'anim', dict = 'amb_rest_lean@world_human_lean_fence_fwd_check_out_livestock@male_e@idle_c', anim = 'idle_g', speed = 2.0, speedX = 2.0, duration = -1, flags = 2 },
    { name = 'lean3', label = 'Lean 3', category = 'idle', gender = 'any', kind = 'anim', dict = 'amb_rest_lean@world_human_lean@post@left@female_a@idle_a', anim = 'idle_a', speed = 2.0, speedX = 2.0, duration = -1, flags = 1 },
    { name = 'lean4', label = 'Lean 4', category = 'idle', gender = 'any', kind = 'anim', dict = 'amb_rest_lean@world_human_lean@post@left@female_a@idle_a', anim = 'idle_b', speed = 2.0, speedX = 2.0, duration = -1, flags = 1 },
    { name = 'lean5', label = 'Lean 5', category = 'idle', gender = 'any', kind = 'anim', dict = 'amb_rest_lean@world_human_lean@post@left@female_a@idle_a', anim = 'idle_c', speed = 2.0, speedX = 2.0, duration = -1, flags = 1 },
    { name = 'lean6', label = 'Lean 6', category = 'idle', gender = 'any', kind = 'anim', dict = 'amb_rest_lean@world_human_lean@wall@right@male_b@idle_a', anim = 'idle_c', speed = 2.0, speedX = 2.0, duration = -1, flags = 1 },
    { name = 'leanback', label = 'Lean Back', category = 'idle', gender = 'any', kind = 'scenario', scenario = 'WORLD_HUMAN_LEAN_BACK_WALL' },
    { name = 'lean', label = 'Lean Back on a Wall', category = 'idle', gender = 'any', kind = 'scenario', scenario = 'WORLD_HUMAN_LEAN_BACK_WALL' },
    { name = 'leanbar', label = 'Lean Bar', category = 'idle', gender = 'any', kind = 'anim', dict = 'script_common@shared_scenarios@stand@bar@lean_2_hands@male_a@react_look@loop@med', anim = 'left', speed = 2.0, speedX = 2.0, duration = -1, flags = 1 },
    { name = 'leanbar2', label = 'Lean Bar 2', category = 'idle', gender = 'any', kind = 'anim', dict = 'script_common@shared_scenarios@stand@bar@lean_2_hands@male_a@react_look@exit@generic', anim = 'front', speed = 2.0, speedX = 2.0, duration = -1, flags = 2 },
    { name = 'leanbar3', label = 'Lean Bar 3', category = 'idle', gender = 'any', kind = 'anim', dict = 'script_common@shared_scenarios@stand@bar@lean_2_hands@male_a@idle_c', anim = 'idle_h', speed = 2.0, speedX = 2.0, duration = -1, flags = 1 },
    { name = 'leanbar4', label = 'Lean Bar 4', category = 'idle', gender = 'any', kind = 'anim', dict = 'script_common@shared_scenarios@stand@bar@lean_2_hands@male_a@idle_b', anim = 'idle_f', speed = 2.0, speedX = 2.0, duration = -1, flags = 1 },
    { name = 'leanf1', label = 'Lean Forward 1', category = 'idle', gender = 'male', kind = 'scenario', scenario = 'WORLD_HUMAN_VAL_BANKTELLER' },
    { name = 'leanf2', label = 'Lean Forward 2', category = 'idle', gender = 'any', kind = 'scenario', scenario = 'WORLD_HUMAN_SHOPKEEPER' },
    { name = 'leanf3', label = 'Lean Forward 3', category = 'idle', gender = 'male', kind = 'scenario', scenario = 'WORLD_HUMAN_SHOP_BROWSE_COUNTER' },
    { name = 'leanf4', label = 'Lean Forward 4', category = 'idle', gender = 'male', kind = 'scenario', scenario = 'WORLD_HUMAN_LEAN_FENCE_FWD_CHECK_OUT_LIVESTOCK' },
    { name = 'leanpostl', label = 'Lean Post L', category = 'idle', gender = 'any', kind = 'scenario', scenario = 'WORLD_HUMAN_LEAN_POST_LEFT' },
    { name = 'leanpostr', label = 'Lean Post R', category = 'idle', gender = 'any', kind = 'scenario', scenario = 'WORLD_HUMAN_LEAN_POST_RIGHT' },
    { name = 'leanrail', label = 'Lean Rail', category = 'idle', gender = 'any', kind = 'scenario', scenario = 'WORLD_HUMAN_LEAN_RAILING' },
    { name = 'leanrail2', label = 'Lean Rail 2', category = 'idle', gender = 'male', kind = 'scenario', scenario = 'WORLD_HUMAN_LEAN_BACK_RAILING' },
    { name = 'leanrail3', label = 'Lean Rail 3', category = 'idle', gender = 'male', kind = 'scenario', scenario = 'WORLD_HUMAN_LEAN_RAILING_DYNAMIC' },
    { name = 'leanraildrink', label = 'Lean Rail Drink', category = 'idle', gender = 'male', kind = 'scenario', scenario = 'WORLD_HUMAN_LEAN_RAILING_DRINKING', gameProp = true },
    { name = 'leanrailsmoke', label = 'Lean Rail Smoke', category = 'idle', gender = 'any', kind = 'scenario', scenario = 'WORLD_HUMAN_LEAN_RAILING_SMOKING' },
    { name = 'leantableknife', label = 'Lean Tableknife', category = 'idle', gender = 'male', kind = 'scenario', scenario = 'WORLD_HUMAN_LEAN_TABLE_SHARPEN_KNIFE', gameProp = true },
    { name = 'leanwalll', label = 'Lean Wall L', category = 'idle', gender = 'male', kind = 'scenario', scenario = 'WORLD_HUMAN_LEAN_WALL_LEFT' },
    { name = 'leanwallr', label = 'Lean Wall R', category = 'idle', gender = 'male', kind = 'scenario', scenario = 'WORLD_HUMAN_LEAN_WALL_RIGHT' },
    { name = 'leanwhittle', label = 'Lean Whittle', category = 'idle', gender = 'male', kind = 'scenario', scenario = 'WORLD_HUMAN_LEAN_BACK_WHITTLE', gameProp = true },
    { name = 'peakwindowl', label = 'Peak Window L', category = 'idle', gender = 'any', kind = 'anim', dict = 'amb_rest_lean@world_human_lean_window_left@male@enter', anim = 'enter', speed = 2.0, speedX = 2.0, duration = -1, flags = 2 },
    { name = 'peakwindowr', label = 'Peak Window R', category = 'idle', gender = 'any', kind = 'anim', dict = 'amb_rest_lean@world_human_lean_window_right@male@enter', anim = 'enter', speed = 2.0, speedX = 2.0, duration = -1, flags = 2 },
    { name = 'pee', label = 'Pee', category = 'idle', gender = 'male', kind = 'scenario', scenario = 'WORLD_HUMAN_PEE' },
    { name = 'pocketmirror', label = 'Pocket Mirror', category = 'idle', gender = 'female', kind = 'scenario', scenario = 'WORLD_HUMAN_POCKET_MIRROR', gameProp = true },
    { name = 'readtable', label = 'Read Table', category = 'idle', gender = 'male', kind = 'scenario', scenario = 'WORLD_HUMAN_LEAN_READ_PAPER', gameProp = true },
    { name = 'standbar', label = 'Stand Bar', category = 'idle', gender = 'any', kind = 'scenario', scenario = 'SC_WORLD_HUMAN_STAND_BAR' },
    { name = 'sternidle', label = 'Stern Idle', category = 'idle', gender = 'male', kind = 'scenario', scenario = 'WORLD_HUMAN_STERNGUY_IDLES' },
    { name = 'stoic', label = 'Stoic', category = 'idle', gender = 'any', kind = 'scenario', scenario = 'WORLD_HUMAN_STARE_STOIC' },
    { name = 'wait', label = 'Wait', category = 'idle', gender = 'any', kind = 'scenario', scenario = 'WORLD_HUMAN_STAND_WAITING' },
    { name = 'wait2', label = 'Wait 2', category = 'idle', gender = 'male', kind = 'scenario', scenario = 'WORLD_HUMAN_STAND_WAITING_CARRYING', gameProp = true },
    { name = 'wait3', label = 'Wait 3', category = 'idle', gender = 'any', kind = 'anim', dict = 'amb_misc@world_human_waiting_impatient@male_b@base', anim = 'base', speed = 2.0, speedX = 2.0, duration = -1, flags = 1 },
    { name = 'wait4', label = 'Wait 4', category = 'idle', gender = 'any', kind = 'anim', dict = 'amb_misc@world_human_waiting_impatient@male_d@idle_b', anim = 'idle_e', speed = 2.0, speedX = 2.0, duration = -1, flags = 1 },
    { name = 'wait5', label = 'Wait 5', category = 'idle', gender = 'any', kind = 'anim', dict = 'amb_misc@world_human_waiting_impatient@male_d@idle_c', anim = 'idle_g', speed = 2.0, speedX = 2.0, duration = -1, flags = 1 },
    { name = 'wallbrace', label = 'Wall Brace', category = 'idle', gender = 'any', kind = 'scenario', scenario = 'WORLD_HUMAN_DRUNK_BRACE_WALL_NO_VOMIT' },
    { name = 'wipesweat', label = 'Wipe Sweat', category = 'idle', gender = 'any', kind = 'anim', dict = 'mech_loco_m@character@arthur@fidgets@weather@sunny_hot@unarmed', anim = 'sweat_face_b', speed = 8.0, speedX = 3.0, duration = 3000, flags = 2 },
    { name = 'back', label = 'Back', category = 'injury', gender = 'any', kind = 'anim', dict = 'mech_loco_m@generic@injured@unarmed@critical_back@idle', anim = 'idle', speed = 2.0, speedX = 2.0, duration = -1, flags = 1 },
    { name = 'bracewall', label = 'Brace Wall', category = 'injury', gender = 'any', kind = 'anim', dict = 'amb_rest_drunk@world_human_drunk_brace_wall@male_b@idle_b', anim = 'idle_f', speed = 2.0, speedX = 2.0, duration = -1, flags = 1 },
    { name = 'chest', label = 'Chest', category = 'injury', gender = 'any', kind = 'anim', dict = 'mech_loco_m@generic@injured@unarmed@chest@idle', anim = 'idle', speed = 2.0, speedX = 2.0, duration = -1, flags = 1 },
    { name = 'collapse', label = 'Collapse', category = 'injury', gender = 'any', kind = 'anim', dict = 'script_story@gua2@ig@ig_walkcollapse', anim = 'gua2_collapse_rf', speed = 2.0, speedX = 2.0, duration = -1, flags = 1 },
    { name = 'cough', label = 'Cough', category = 'injury', gender = 'any', kind = 'anim', dict = 'ai_gestures@gen_male@standing@speaker@rt_hand', anim = 'cough_low_l_001', speed = 2.0, speedX = 2.0, duration = -1, flags = 0 },
    { name = 'cough2', label = 'Cough 2', category = 'injury', gender = 'any', kind = 'anim', dict = 'ai_gestures@gen_male@standing@speaker@rt_hand', anim = 'cough_high_l_001', speed = 2.0, speedX = 2.0, duration = -1, flags = 0 },
    { name = 'cough3', label = 'Cough 3', category = 'injury', gender = 'any', kind = 'anim', dict = 'ai_gestures@gen_female@standing@speaker@rt_hand', anim = 'cough_low_l_001', speed = 2.0, speedX = 2.0, duration = -1, flags = 0 },
    { name = 'cough4', label = 'Cough 4', category = 'injury', gender = 'any', kind = 'anim', dict = 'ai_gestures@gen_female@standing@speaker@rt_hand', anim = 'cough_high_l_001', speed = 2.0, speedX = 2.0, duration = -1, flags = 0 },
    { name = 'head', label = 'Head', category = 'injury', gender = 'any', kind = 'anim', dict = 'mech_loco_m@generic@injured@unarmed@head@idle', anim = 'idle', speed = 2.0, speedX = 2.0, duration = -1, flags = 1 },
    { name = 'hurl', label = 'Hurl', category = 'injury', gender = 'any', kind = 'kit', hash = -1118911493 },
    { name = 'leftleg', label = 'Left Leg', category = 'injury', gender = 'any', kind = 'anim', dict = 'mech_loco_m@generic@injured@unarmed@left_leg@idle', anim = 'idle', speed = 2.0, speedX = 2.0, duration = -1, flags = 31 },
    { name = 'leftshoulder', label = 'Left Shoulder', category = 'injury', gender = 'any', kind = 'anim', dict = 'mech_loco_m@character@arthur@injured@left_shoulder@unarmed@idle', anim = 'idle', speed = 2.0, speedX = 2.0, duration = -1, flags = 31 },
    { name = 'neck', label = 'Neck', category = 'injury', gender = 'any', kind = 'anim', dict = 'mech_loco_m@generic@injured@unarmed@critical_neck_right@idle', anim = 'idle', speed = 2.0, speedX = 2.0, duration = -1, flags = 1 },
    { name = 'drunkpassout2', label = 'Passed Out Drunk 2', category = 'injury', gender = 'male', kind = 'scenario', scenario = 'WORLD_HUMAN_DRUNK_PASSED_OUT_FLOOR' },
    { name = 'rightarm', label = 'Right Arm', category = 'injury', gender = 'any', kind = 'anim', dict = 'mech_loco_m@generic@injured@unarmed@right_arm@idle', anim = 'idle', speed = 2.0, speedX = 2.0, duration = -1, flags = 31 },
    { name = 'sick', label = 'Sick', category = 'injury', gender = 'any', kind = 'anim', dict = 'amb_wander@upperbody_idles@sick@both_arms@male_a@idle_a', anim = 'idle_c', speed = 2.0, speedX = 2.0, duration = -1, flags = 1 },
    { name = 'sneeze', label = 'Sneeze', category = 'injury', gender = 'any', kind = 'anim', dict = 'mech_loco_m@character@arthur@fidgets@weather@rainy_wet@unarmed', anim = 'sneeze_a', speed = 2.0, speedX = 2.0, duration = -1, flags = 0 },
    { name = 'uncomfortable', label = 'Uncomfortable', category = 'injury', gender = 'any', kind = 'anim', dict = 'script_story@fin2@ig@ig2_chase_cleet', anim = 'civilian_injured_loop_a_civilian', speed = 2.0, speedX = 2.0, duration = -1, flags = 1 },
    { name = 'vomit', label = 'Vomit', category = 'injury', gender = 'any', kind = 'anim', dict = 'amb_misc@world_human_vomit@male_a@idle_b', anim = 'idle_f', speed = 2.0, speedX = 2.0, duration = -1, flags = 1 },
    { name = 'vomitkneel', label = 'Vomit Kneel', category = 'injury', gender = 'male', kind = 'scenario', scenario = 'WORLD_HUMAN_VOMIT_KNEEL' },
    { name = 'writhe', label = 'Writhe', category = 'injury', gender = 'any', kind = 'anim', dict = 'ai_combat@damage@writhe@death', anim = 'death_a', speed = 2.0, speedX = 2.0, duration = -1, flags = 2 },
    { name = 'writhe2', label = 'Writhe 2', category = 'injury', gender = 'any', kind = 'anim', dict = 'ai_combat@damage@injured_pistol@to_writhe', anim = 'variation_d', speed = 2.0, speedX = 2.0, duration = -1, flags = 2 },
    { name = 'writhe3', label = 'Writhe 3', category = 'injury', gender = 'any', kind = 'anim', dict = 'ai_combat@damage@injured_pistol@to_writhe', anim = 'variation_c', speed = 2.0, speedX = 2.0, duration = -1, flags = 2 },
    { name = 'bookground', label = 'Bookground', category = 'sitting', gender = 'male', kind = 'scenario', scenario = 'WORLD_HUMAN_SIT_GROUND_READING_BOOK_STOW', gameProp = true },
    { name = 'drinkground', label = 'Drink Ground', category = 'sitting', gender = 'male', kind = 'scenario', scenario = 'WORLD_HUMAN_BUCKET_DRINK_GROUND', gameProp = true },
    { name = 'drunkpassout', label = 'Drunk Passout', category = 'sitting', gender = 'any', kind = 'scenario', scenario = 'WORLD_HUMAN_SIT_GROUND_DRINKING_DRUNK_PASSED_OUT', gameProp = true },
    { name = 'drunkslump', label = 'Drunk Slump', category = 'sitting', gender = 'male', kind = 'scenario', scenario = 'WORLD_HUMAN_DRUNK_BAR_SLUMPED' },
    { name = 'guitar2', label = 'Guitar (Downbeat)', category = 'sitting', gender = 'male', kind = 'scenario', scenario = 'WORLD_HUMAN_SIT_GUITAR_DOWNBEAT', gameProp = true },
    { name = 'guitar', label = 'Guitar (Upbeat)', category = 'sitting', gender = 'male', kind = 'scenario', scenario = 'WORLD_HUMAN_SIT_GUITAR_UPBEAT', gameProp = true },
    { name = 'ledgeharm', label = 'Harmonica on a Ledge', category = 'sitting', gender = 'any', kind = 'scenario', scenario = 'WORLD_HUMAN_SEAT_LEDGE_HARMONICA', gameProp = true },
    { name = 'kneel', label = 'Kneel', category = 'sitting', gender = 'any', kind = 'anim', dict = 'MECH_DYNAMIC@WORLD_PLAYER_DYNAMIC_KNEEL_GROUND@GENERIC@MALE_A@base', anim = 'base', speed = 2.0, speedX = 2.0, duration = -1, flags = 2 },
    { name = 'kneel2', label = 'Kneel 2', category = 'sitting', gender = 'any', kind = 'anim', dict = 'mech_dynamic@world_player_dynamic_kneel_ground@cook@stick@male_a@idle_b', anim = 'idle_e', speed = 2.0, speedX = 2.0, duration = -1, flags = 1 },
    { name = 'kneel3', label = 'Kneel 3', category = 'sitting', gender = 'any', kind = 'anim', dict = 'mech_dynamic@world_player_dynamic_kneel_ground@generic@male_a@react_look@loop@generic', anim = 'react_look_backleft_loop', speed = 2.0, speedX = 2.0, duration = -1, flags = 1 },
    { name = 'kneel4', label = 'Kneel 4', category = 'sitting', gender = 'any', kind = 'anim', dict = 'mech_dynamic@world_player_dynamic_kneel_ground@cook@grill2@male_a@use_idles_meat_b@idle_a', anim = 'idle_c', speed = 2.0, speedX = 2.0, duration = -1, flags = 1 },
    { name = 'layground', label = 'Lay Ground', category = 'sitting', gender = 'male', kind = 'scenario', scenario = 'WORLD_CAMP_FIRE_LAY_BACK_GROUND' },
    { name = 'layground2', label = 'Layground 2', category = 'sitting', gender = 'any', kind = 'scenario', scenario = 'WORLD_CAMP_FIRE_LAY_GROUND_SIDE' },
    { name = 'newsground', label = 'Newsground', category = 'sitting', gender = 'male', kind = 'scenario', scenario = 'WORLD_HUMAN_SIT_GROUND_READ_NEWSPAPER', gameProp = true },
    { name = 'newspaper', label = 'Newspaper', category = 'sitting', gender = 'any', kind = 'anim', dict = 'amb_rest_sit@world_human_sit_ground@reading@newspaper@male_a@react_look@loop@generic', anim = 'react_look_front_loop', speed = 2.0, speedX = 2.0, duration = -1, flags = 1,
      prop = { model = 'p_cs_newspaper_01x', bone = 22798, x = -0.15, y = -0.13, z = -0.05, rx = -30.0, ry = 90.0, rz = 10.0 } },
    { name = 'newspaper2', label = 'Newspaper 2', category = 'sitting', gender = 'any', kind = 'anim', dict = 'amb_rest_sit@world_human_sit_ground@reading@newspaper@male_a@stand_enter_withprop', anim = 'enter_back_rf', speed = 2.0, speedX = 2.0, duration = -1, flags = 2,
      prop = { model = 'p_cs_newspaper_01x', bone = 22798, x = -0.15, y = -0.13, z = -0.08, rx = -30.0, ry = 90.0, rz = 18.0 } },
    { name = 'passout', label = 'Passout', category = 'sitting', gender = 'male', kind = 'scenario', scenario = 'WORLD_HUMAN_DRUNK_PASSED_OUT_FLOOR' },
    { name = 'passout2', label = 'Passout 2', category = 'sitting', gender = 'any', kind = 'anim', dict = 'amb_rest@world_human_passed_out_floor@male_a@stand_enter', anim = 'enter_back_lf', speed = 2.0, speedX = 2.0, duration = -1, flags = 2 },
    { name = 'prone', label = 'Prone', category = 'sitting', gender = 'any', kind = 'anim', dict = 'mech_crawl@prone2crawlfront', anim = 'front_armsdown', speed = 2.0, speedX = 2.0, duration = -1, flags = 2 },
    { name = 'readjournal', label = 'Read Journal', category = 'sitting', gender = 'female', kind = 'scenario', scenario = 'WORLD_HUMAN_SIT_GROUND_READING_JOURNAL', gameProp = true },
    { name = 'sitcoffee', label = 'Sit Coffee', category = 'sitting', gender = 'any', kind = 'scenario', scenario = 'WORLD_HUMAN_SIT_GROUND_COFFEE_DRINK', gameProp = true },
    { name = 'sitfire', label = 'Sit Fire', category = 'sitting', gender = 'male', kind = 'scenario', scenario = 'WORLD_HUMAN_FIRE_SIT' },
    { name = 'sitground1', label = 'Sit Ground 1', category = 'sitting', gender = 'any', kind = 'scenario', scenario = 'WORLD_CAMP_FIRE_SIT_GROUND' },
    { name = 'sitground2', label = 'Sit Ground 2', category = 'sitting', gender = 'any', kind = 'scenario', scenario = 'WORLD_CAMP_FIRE_SIT_GROUND_RECLINE' },
    { name = 'sitground3', label = 'Sit Ground 3', category = 'sitting', gender = 'any', kind = 'scenario', scenario = 'WORLD_CAMP_FIRE_SEATED_GROUND' },
    { name = 'sitgroundsmoke', label = 'Sit Ground Smoke', category = 'sitting', gender = 'any', kind = 'scenario', scenario = 'WORLD_HUMAN_SIT_SMOKE', gameProp = true },
    { name = 'sitguitar1', label = 'Sit Guitar 1', category = 'sitting', gender = 'male', kind = 'scenario', scenario = 'WORLD_HUMAN_SIT_GUITAR', gameProp = true },
    { name = 'sitguitar2', label = 'Sit Guitar 2', category = 'sitting', gender = 'male', kind = 'scenario', scenario = 'WORLD_HUMAN_SIT_GUITAR_UPBEAT', gameProp = true },
    { name = 'sitguitar3', label = 'Sit Guitar 3', category = 'sitting', gender = 'male', kind = 'scenario', scenario = 'WORLD_HUMAN_SIT_GUITAR_DOWNBEAT', gameProp = true },
    { name = 'sitread', label = 'Sit Read', category = 'sitting', gender = 'any', kind = 'anim', dict = 'amb_rest_sit@world_human_sit_ground@read_book@male_a@react_look@enter@high', anim = 'react_look_front_enter', speed = 2.0, speedX = 2.0, duration = -1, flags = 2,
      prop = { model = 'p_journal_open01x', bone = 22798, x = 0.1, y = 0.07, z = -0.08, rx = 0.0, ry = 180.0, rz = 70.0 } },
    { name = 'sitread2', label = 'Sit Read 2', category = 'sitting', gender = 'any', kind = 'anim', dict = 'amb_rest_sit@world_human_sit_ground@sketching@female_a@react_look@active_look', anim = 'active_front_look', speed = 2.0, speedX = 2.0, duration = -1, flags = 1,
      prop = { model = 'p_journal_open01x', bone = 34606, x = 0.0, y = 0.15, z = 0.18, rx = -70.0, ry = 240.0, rz = 30.0 } },
    { name = 'sitguitar', label = 'Sit With a Guitar', category = 'sitting', gender = 'male', kind = 'scenario', scenario = 'WORLD_HUMAN_SIT_GUITAR', gameProp = true },
    { name = 'sleep', label = 'Sleep', category = 'sitting', gender = 'any', kind = 'anim', dict = 'amb_rest@world_human_passed_out_floor@male_a@idle_a', anim = 'idle_b', speed = 2.0, speedX = 2.0, duration = -1, flags = 2 },
    { name = 'sleep2', label = 'Sleep 2', category = 'sitting', gender = 'any', kind = 'scenario', scenario = 'WORLD_HUMAN_SLEEP_GROUND_PILLOW' },
    { name = 'whittleground', label = 'Whittle Ground', category = 'sitting', gender = 'male', kind = 'scenario', scenario = 'WORLD_HUMAN_SIT_GROUND_WHITTLE', gameProp = true },
    { name = 'bartend', label = 'Bartend', category = 'working', gender = 'male', kind = 'scenario', scenario = 'WORLD_HUMAN_BAR_DRINK_BARTENDER', gameProp = true },
    { name = 'broom', label = 'Broom', category = 'working', gender = 'male', kind = 'scenario', scenario = 'WORLD_HUMAN_PUSH_BROOM_WORKING', gameProp = true },
    { name = 'broom2', label = 'Broom 2', category = 'working', gender = 'any', kind = 'scenario', scenario = 'WORLD_HUMAN_STRAW_BROOM_WORKING', gameProp = true },
    { name = 'browse', label = 'Browse', category = 'working', gender = 'female', kind = 'scenario', scenario = 'WORLD_HUMAN_SHOP_BROWSE' },
    { name = 'bucketfeed', label = 'Bucket Feed', category = 'working', gender = 'male', kind = 'scenario', scenario = 'WORLD_HUMAN_FEED_PIGS', gameProp = true },
    { name = 'cleanglass', label = 'Clean Glass', category = 'working', gender = 'any', kind = 'scenario', scenario = 'WORLD_HUMAN_BARTENDER_CLEAN_GLASS', gameProp = true },
    { name = 'cleantable', label = 'Clean Table', category = 'working', gender = 'any', kind = 'scenario', scenario = 'WORLD_HUMAN_CLEAN_TABLE', gameProp = true },
    { name = 'cleanwindow', label = 'Clean Window', category = 'working', gender = 'any', kind = 'anim', dict = 'script_common@other@unapproved', anim = 'windowwasher_wash_loop', speed = 2.0, speedX = 2.0, duration = -1, flags = 1 },
    { name = 'clipboard', label = 'Clipboard', category = 'working', gender = 'male', kind = 'scenario', scenario = 'WORLD_HUMAN_CLIPBOARD', gameProp = true },
    { name = 'cook', label = 'Cook', category = 'working', gender = 'any', kind = 'anim', dict = 'mech_dynamic@world_player_dynamic_kneel_ground@cook@knife@male_a@idle_b', anim = 'idle_d', speed = 2.0, speedX = 2.0, duration = -1, flags = 1 },
    { name = 'cook2', label = 'Cook 2', category = 'working', gender = 'male', kind = 'scenario', scenario = 'WORLD_HUMAN_CANNED_FOOD_COOKING', gameProp = true },
    { name = 'feedchicken', label = 'Feed Chicken', category = 'working', gender = 'any', kind = 'scenario', scenario = 'WORLD_HUMAN_FEED_CHICKEN', gameProp = true },
    { name = 'bucketfeed2', label = 'Feed the Chickens', category = 'working', gender = 'male', kind = 'scenario', scenario = 'WORLD_PLAYER_CHORES_FEED_CHICKENS', gameProp = true },
    { name = 'bucketfill', label = 'Fill a Bucket', category = 'working', gender = 'any', kind = 'scenario', scenario = 'WORLD_HUMAN_BUCKET_FILL', gameProp = true },
    { name = 'fire2', label = 'Fire 2', category = 'working', gender = 'male', kind = 'scenario', scenario = 'WORLD_HUMAN_FIRE_TEND_KNEEL' },
    { name = 'inspect', label = 'Inspect', category = 'working', gender = 'any', kind = 'scenario', scenario = 'WORLD_HUMAN_CROUCH_INSPECT' },
    { name = 'inspect2', label = 'Inspect 2', category = 'working', gender = 'any', kind = 'anim', dict = 'amb_work@world_human_crouch_inspect@male_a@base', anim = 'base', speed = 2.0, speedX = 2.0, duration = -1, flags = 1 },
    { name = 'inspect3', label = 'Inspect 3', category = 'working', gender = 'any', kind = 'scenario', scenario = 'WORLD_HUMAN_INSPECT' },
    { name = 'note', label = 'Note', category = 'working', gender = 'any', kind = 'kit', hash = -1169051375, gameProp = true },
    { name = 'notebook', label = 'Notebook', category = 'working', gender = 'any', kind = 'scenario', scenario = 'WORLD_HUMAN_WRITE_NOTEBOOK', gameProp = true },
    { name = 'oilhigh', label = 'Oil High', category = 'working', gender = 'male', kind = 'scenario', scenario = 'WORLD_HUMAN_REPAIR_HIGH_OILCAN', gameProp = true },
    { name = 'oilmid', label = 'Oil Mid', category = 'working', gender = 'male', kind = 'scenario', scenario = 'WORLD_HUMAN_REPAIR_MED_OILCAN', gameProp = true },
    { name = 'bucketpour', label = 'Pour a Bucket', category = 'working', gender = 'any', kind = 'scenario', scenario = 'WORLD_HUMAN_BUCKET_POUR_LOW', gameProp = true },
    { name = 'preacher', label = 'Preacher', category = 'working', gender = 'male', kind = 'scenario', scenario = 'SC_WORLD_HUMAN_PREACHER', gameProp = true },
    { name = 'rake', label = 'Rake', category = 'working', gender = 'male', kind = 'scenario', scenario = 'WORLD_HUMAN_FARMER_RAKE', gameProp = true },
    { name = 't2', label = 'Repair a Small Wheel', category = 'working', gender = 'male', kind = 'scenario', scenario = 'PROP_HUMAN_REPAIR_WAGON_WHEEL_ON_SMALL' },
    { name = 't1', label = 'Repair a Wagon Wheel', category = 'working', gender = 'male', kind = 'scenario', scenario = 'PROP_HUMAN_REPAIR_WAGON_WHEEL_ON_LARGE' },
    { name = 'servebeer', label = 'Serve Beer', category = 'working', gender = 'any', kind = 'anim', dict = 'amb_work@world_human_bartender@serve_beer@male_a@return_bottle@over_bar@react_look@enter@low', anim = 'react_look_front_enter', speed = 2.0, speedX = 2.0, duration = -1, flags = 0,
      prop = { model = 'p_bottleBeer01a', bone = 22798, x = 0.06, y = -0.08, z = -0.05, rx = -80.0, ry = 0.0, rz = -10.0 } },
    { name = 'servewhiskey', label = 'Serve Whiskey', category = 'working', gender = 'male', kind = 'anim', dict = 'amb_work@world_human_bartender@serve_whiskey@male_a@pour_glass@over_bar@react_look@enter@low', anim = 'react_look_front_enter', speed = 2.0, speedX = -8.0, duration = -1, flags = 0,
      prop = { model = 'p_whiskeyglass01x', bone = 34606, x = 0.09, y = 0.02, z = 0.05, rx = 210.0, ry = 0.0, rz = 0.0 } },
    { name = 'sledgehammer', label = 'Sledgehammer', category = 'working', gender = 'male', kind = 'scenario', scenario = 'WORLD_HUMAN_SLEDGEHAMMER', gameProp = true },
    { name = 'takecoins', label = 'Take Coins', category = 'working', gender = 'any', kind = 'anim', dict = 'mech_dynamic@prop_player_food_order@bar@stew@bartender@action', anim = 'action', speed = 2.0, speedX = 2.0, duration = -1, flags = 0 },
    { name = 'takecoins2', label = 'Take Coins 2', category = 'working', gender = 'any', kind = 'anim', dict = 'mech_dynamic@prop_player_shot_order@bar@bartender@action', anim = 'action', speed = 2.0, speedX = 2.0, duration = -1, flags = 0 },
    { name = 'washdishes', label = 'Wash Dishes', category = 'working', gender = 'female', kind = 'scenario', scenario = 'WORLD_HUMAN_WASH_DISHES_TABLE_LEFT', gameProp = true },
    { name = 'weeding', label = 'Weeding', category = 'working', gender = 'male', kind = 'scenario', scenario = 'WORLD_HUMAN_FARMER_WEEDING' },
    { name = 'wrench', label = 'Wrench', category = 'working', gender = 'male', kind = 'scenario', scenario = 'WORLD_HUMAN_REPAIR_HIGH_WRENCH', gameProp = true },
}
