Translations = {}

Translations.en = {
    -- Prompts
    PROMPT_OPEN         = "Auction House",

    -- Notifications
    LISTING_CREATED     = "Listed %s (x%d) — Starting bid: $%.2f",
    LISTING_CANCELLED   = "Listing cancelled. Item returned to mailbox.",
    BID_PLACED          = "Bid of $%.2f placed on %s!",
    BID_OUTBID          = "You've been outbid on %s! Your $%.2f has been refunded.",
    BUYOUT_SUCCESS      = "Purchased %s (x%d) for $%.2f!",
    ITEM_COLLECTED      = "Collected %s from mailbox.",
    MONEY_COLLECTED     = "Collected $%.2f from mailbox.",
    MAILBOX_FULL        = "Your mailbox is full! Collect items before listing more.",
    MAX_LISTINGS        = "You've reached the maximum of %d active listings.",
    NOT_ENOUGH_MONEY    = "You don't have enough money.",
    ITEM_BLACKLISTED    = "This item cannot be auctioned.",
    INVALID_PRICE       = "Invalid price. Must be between $%.2f and $%.2f.",
    BID_TOO_LOW         = "Bid must be at least $%.2f.",
    CANNOT_BID_OWN      = "You cannot bid on your own listing.",
    DEPOSIT_CHARGED     = "Deposit of $%.2f charged.",
    NO_ITEMS            = "You have no items to auction.",
    EXPIRED_RETURNED    = "Your listing for %s expired. Item returned to mailbox.",
    SALE_COMPLETE       = "Your %s sold for $%.2f! (Tax: $%.2f) — Collect from mailbox.",
    AUCTION_CANCELLED   = "Auction cancelled.",
    CANCEL_HAS_BIDS     = "Cannot cancel — this listing has active bids.",
    LISTING_NOT_FOUND   = "Listing not found or already completed.",
    COLLECT_FAILED      = "Failed to collect. Try again.",
    ITEM_REMOVED_FAIL   = "Failed to remove item from your inventory.",
    LISTING_CHANGED     = "That listing just changed or closed. Your $%.2f was returned.",
    REQUEST_FAILED      = "Could not post your request. $%.2f escrow refunded.",
    ORDER_FAILED        = "Could not place your order. $%.2f refunded.",

    -- NUI translations table (sent to the UI)
    NUI = {
        TITLE               = "AUCTION HOUSE",
        TAB_BROWSE          = "Browse",
        TAB_SELL            = "Sell",
        TAB_MY_AUCTIONS     = "My Auctions",
        TAB_MAILBOX         = "Mailbox",
        SEARCH_PLACEHOLDER  = "Search items...",
        SORT_PRICE_ASC      = "Price: Low → High",
        SORT_PRICE_DESC     = "Price: High → Low",
        SORT_TIME_ASC       = "Time: Ending Soon",
        SORT_TIME_DESC      = "Time: Newest",
        SORT_NAME           = "Name: A → Z",
        COL_ITEM            = "Item",
        COL_QUANTITY         = "Qty",
        COL_CURRENT_BID     = "Current Bid",
        COL_BUYOUT          = "Buyout",
        COL_TIME_LEFT       = "Time Left",
        COL_SELLER          = "Seller",
        COL_BIDS            = "Bids",
        BTN_BID             = "Bid",
        BTN_BUYOUT          = "Buy Now",
        BTN_CANCEL          = "Cancel",
        BTN_COLLECT         = "Collect",
        BTN_COLLECT_ALL     = "Collect All",
        BTN_LIST_ITEM       = "List Item",
        LBL_START_PRICE     = "Starting Price ($)",
        LBL_BUYOUT_PRICE    = "Buyout Price ($)",
        LBL_DURATION        = "Duration",
        LBL_DEPOSIT         = "Deposit",
        LBL_TAX_RATE        = "Sales Tax",
        LBL_CATEGORY        = "Category",
        LBL_QTY             = "Quantity",
        LBL_NO_RESULTS      = "No auctions found.",
        LBL_NO_ITEMS        = "Nothing in your inventory to auction.",
        LBL_EMPTY_MAILBOX   = "Your mailbox is empty.",
        LBL_CONFIRM_BID     = "Place bid of $%s on %s?",
        LBL_CONFIRM_BUYOUT  = "Buy %s (x%s) now for $%s?",
        LBL_CONFIRM_CANCEL  = "Cancel listing for %s? Item will be returned to your mailbox.",
        LBL_TOTAL_LISTINGS  = "%d listings",
        LBL_SELECT_ITEM     = "Select an item from your inventory to list.",
        LBL_FEE_BREAKDOWN   = "Fee Breakdown",
        LBL_STATUS_ACTIVE   = "Active",
        LBL_STATUS_SOLD     = "Sold",
        LBL_STATUS_EXPIRED  = "Expired",
        LBL_STATUS_CANCELLED = "Cancelled",
        LBL_ITEM_RETURN     = "Item returned",
        LBL_MONEY_EARNED    = "Money earned",
        LBL_BID_REFUND      = "Bid refund",
        TIME_HOURS          = "%dh",
        TIME_MINUTES        = "%dm",
        TIME_SECONDS        = "%ds",
        TIME_EXPIRED        = "Expired",

        -- ---- CATALOGUE TAB ----
        TAB_CATALOGUE           = "Order Catalogue",
        CAT_ALL                 = "All Items",
        CAT_MATERIALS           = "Materials",
        CAT_FOOD                = "Food & Provisions",
        CAT_TOOLS               = "Tools",
        CAT_MEDICAL             = "Medical",
        CAT_TOBACCO             = "Tobacco",
        CAT_SPIRITS             = "Spirits",
        CAT_COMPANY_ALL         = "All Companies",
        CATALOGUE_SEARCH_PH     = "Search catalog...",
        BTN_ORDER               = "Order",
        BTN_MY_ORDERS           = "My Orders",
        LBL_PRICE_PER_UNIT      = "Price / unit",
        LBL_SHIPPING_FEE        = "Shipping & Handling",
        LBL_TOTAL_COST          = "Order Total",
        LBL_QTY_ORDER           = "Quantity",
        LBL_MAX_QTY             = "Max %d per order",
        LBL_NO_ORDERS           = "No orders yet.",
        LBL_EST_DELIVERY        = "Est. delivery",
        ORDER_STATUS_PROCESSING       = "Processing",
        ORDER_STATUS_IN_TRANSIT       = "In Transit",
        ORDER_STATUS_OUT_FOR_DELIVERY = "Out for Delivery",
        ORDER_STATUS_DELIVERED        = "Delivered",
        ORDER_STATUS_CANCELLED        = "Cancelled",
        BTN_CANCEL_ORDER        = "Cancel Order",

        -- ---- REQUESTS TAB ----
        TAB_REQUESTS            = "Want Requests",
        BTN_BROWSE_REQUESTS     = "Browse",
        BTN_POST_REQUEST        = "Post Request",
        BTN_MY_REQUESTS         = "My Requests",
        BTN_FULFILL             = "Fulfill",
        BTN_CANCEL_REQUEST      = "Cancel",
        REQUESTS_SEARCH_PH      = "Search by item name...",
        LBL_QTY_REMAINING       = "Qty Remaining",
        LBL_PAY_PER_UNIT        = "Pay / Unit",
        LBL_TOTAL_VALUE         = "Total Value",
        LBL_REQUESTER           = "Posted By",
        LBL_ESCROW_LEFT         = "Escrow Left",
        LBL_QTY_FILLED          = "Filled",
        LBL_ESCROW_REQUIRED     = "Escrow Required",
        LBL_SELLER_TAX          = "Seller Tax",
        LBL_YOU_RECEIVE         = "You Receive",
        LBL_NO_REQUESTS         = "No open requests found.",
        REQ_STATUS_OPEN         = "Open",
        REQ_STATUS_PARTIAL      = "Partial",
        REQ_STATUS_FILLED       = "Filled",
        REQ_STATUS_CANCELLED    = "Cancelled",
        REQ_STATUS_EXPIRED      = "Expired",
        LBL_PERSISTENT          = "Persistent",
        LBL_YOUR_INV            = "In Your Inventory",
        LBL_FULFILL_CONFIRM     = "Sell to Requester",
        LBL_REQUEST_ITEM        = "Item Name",
        LBL_REQUEST_LABEL       = "Display Name",
        LBL_DURATION            = "Duration",
        LBL_EXPIRES             = "Expires",
    },
}

-- ============================================================================
-- Translation helper
-- ============================================================================
function T(key, ...)
    local lang = Config.Language or 'en'
    local str = Translations[lang] and Translations[lang][key] or Translations.en[key] or key
    if type(str) == 'table' then return str end
    local args = {...}
    if #args > 0 then return string.format(str, table.unpack(args)) end
    return str
end
